### ISSUE TITLE
Can I use postcss.config.js?

### ISSUE THREAD

**Issue by jvanbaarsen** [rails/webpacker#1002]
Is there a way to use `postcss.config.js` instead of the yml file? I'm trying to get Tailwindcss (https://tailwindcss.com/docs/installation/) running, but they seem to require setting up some extra config variables in the postcss.config.js:

```
var tailwindcss = require('tailwindcss');
module.exports = {
  plugins: [
    // ...
    tailwindcss('./path/to/your/tailwind-config.js'),
    require('autoprefixer'),
    // ...
  ]
}
```

There is a good change I'm asking this in totally the wrong place, if so you can close this. Reason I'm asking here, is because the docs says that postcss-loader is included in webpacker, and it comes with a .postcssrc by default.

**Comment by gauravtiwari** [comment]
Is adding the plugin to the list doesn't work?

```
plugins:
  postcss-smart-import: {}
  postcss-cssnext: {}
  tailwindcss: { config: 'path to config' }
```
