### ISSUE TITLE
Compiling… Compilation failed: lists Gemfiles, no error message

### ISSUE THREAD

**Issue by joshRpowell** [rails/webpacker#1028]
Running
```
Bundler version 1.16.0
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
Spring version 2.0.2
Rails 5.1.4
npm 5.5.1
node v8.9.1
nvm 0.33.0
```

I get the following on precompile on my local: 
```
•100% [I] ➜ RAILS_ENV=production bin/bundle exec rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment

** Invoke yarn:install (first_time)
** Execute yarn:install
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.74s.
** Execute assets:precompile
** Invoke webpacker:compile (first_time)
** Invoke webpacker:verify_install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Invoke webpacker:check_binstubs (first_time)
** Execute webpacker:check_binstubs
** Execute webpacker:verify_install
Webpacker is installed 🎉 🍰
Using /Users/jpowell/Dropbox/Clients/milner-crm/config/webpacker.yml file for setting up webpack paths
** Invoke environment
** Execute webpacker:compile
Compiling…
Compilation failed:
Using rake 12.3.0
Using concurrent-ruby 1.0.5
Using aasm 4.12.3
.
.
.
Using zip-zip 0.3
Bundle complete! 193 Gemfile dependencies, 428 gems now installed.
Gems in the group production were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Cleaning all the gems on your system is dangerous! If you're sure you want to
remove every system gem not in this bundle, run `bundle clean --force`.
```

webpacker.yml:
```yaml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: true
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```

package.json
```json
{
  "version": "1.0.0",
  "dependencies": {
    "@rails/webpacker": "^3.0.2",
    "babel-preset-react": "^6.24.1",
    "coffeescript": "1.12.7",
    "history": "~2.0.1",
    "hyperscript": "^2.0.2",
    "infiniscroll": "^1.1.0",
    "lighthouse": "^1.4.1",
    "multicb": "^1.2.1",
    "prop-types": "^15.6.0",
    "react": "^16.1.0",
    "react-addons-create-fragment": "^15.6.2",
    "react-data-grid": "^2.0.73",
    "react-datepicker": "^0.61.0",
    "react-dom": "^16.1.0",
    "react-paginate": "^5.0.0",
    "react-redux": "~4.4.1",
    "react-router": "3.2.0",
    "react-router-redux": "~4.0.0",
    "react-typeahead": "^2.0.0-alpha.6",
    "react_ujs": "^2.4.1",
    "reactify": "^1.1.1",
    "redux": "^3.3.1",
    "redux-actions": "~2.2.1",
    "redux-devtools": "^3.4.0",
    "redux-devtools-dock-monitor": "~1.1.0",
    "redux-devtools-log-monitor": "~1.4.0",
    "redux-thunk": "~2.2.0"
  },
  "license": "MIT",
  "engines": {
    "node": "^8.0",
    "npm": "^5.5"
  },
  "devDependencies": {
    "eslint": "^2.10.2",
    "webpack-dev-server": "^2.9.4"
  }
}
```

.babelrc
```json
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": true
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}
```
