### ISSUE TITLE
Base webpacker.yml Environments on Rails ENV

### ISSUE THREAD

**Issue by JanStevens** [rails/webpacker#1030]
Hello,

We have a couple of additional environments in our rails application:

- test: Testing environment
- edge: Automatic CI deployments of cutting edge code
- demo: Sales environment for demonstrations
- translate: Special environment for translating our rails app using phrase app
- benchmark: Special environment for jmeter benchmarks
- production: production

We come from the sprockets asset pipe line and we could fine tune it for every environment. For example in CI when in test env we would precompile assets and use production precompiled assets during test (both for speed and to verify that the production assets are actually precompiled correctly).

This brings me to my problem, webpacker also uses `NODE_ENV` which is used in every package and always should be `production` when you are running on a server (just grep on `NODE_ENV` in your node_modules). Since webpacker is so tied in with `NODE_ENV` configuration wise this only allows me to define two possible configurations: dev and production.

Coming from sprockets where I could have different assets configuration based on the RAILS_ENV, I lose a bunch of configuration. Things like asset syncing to S3 bucket for different environments suddenly becomes impossible, for example: `NODE_ENV=production RAILS_ENV=translation` but I want those files generated in packs-translate so I can sync packs-translate to S3 bucket translate. Also translate env includes some additional dependencies for the phrase app that should not be on production.

I suggest to use the `RAILS_ENV` in webpacker configuration and let the `NODE_ENV` alone. I would even go as far declaring that every webpack js file is based on a `RAILS_ENV`.

**Comment by gauravtiwari** [comment]
@JanStevens I think you can do more or less same thing with webpacker as well although since `production` adds special meaning to webpacker and npm packages you won't get same benefits - like minification in your custom environment. 

What you could do is create a `translate.js` file inside `config/webpack` and inherit it from production. That way it will behave like production environment and you can customise paths from `webpacker.yml`

```js
// webpack/translate.js
const config = require('./production')

module.exports = config
```

```yml
# webpacker.yml

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

translate:
  <<: *default
  # Production depends on precompilation of packs prior to booting for performance.

  compile: false

  public_output_path: packs-translate
```

![screen shot 2017-12-11 at 12 44 14](https://user-images.githubusercontent.com/771039/33831722-1397a2e2-de71-11e7-8672-288b7fda84e4.png)

Is that what you need?
