### ISSUE TITLE
Webpacker and CSP

### ISSUE THREAD

**Issue by guilleiguaran** [rails/webpacker#1057]
I'm opening this to keep track of the issues found when trying to use webpacker along with new Rails 5.2 CSP DSL.

- [x] `cheap-eval-source-map` devtool can't be used with `unsafe-eval`, Fixed: #1046
- [ ] Vue templates are unusable with `unsafe-eval`, [reference](https://vuejs.org/v2/guide/installation.html#CSP-environments)
- [ ] dev server requires allowing `ws://localhost:3035` and `http://localhost:3035` as `connect-src`
- [ ]  do we need to use `__webpack_nonce__` ?, [reference](https://github.com/webpack/webpack/pull/3210)

**Comment by renchap** [comment]
I have a pretty strict CSP policy for some time in my app, using Webpacker and React.
You need `script-src: unsafe-eval` if you use `react-hot-loader`. I also added `ws://localhost:3000 http://localhost:3035 ws://localhost:3035` to `connect-src`, but I am not sure all of them are still needed with the new Rack proxy. The source maps should also be set to `cheap-module-source-map` (https://reactjs.org/docs/cross-origin-errors.html#source-maps) but this is already done.

React does not need any other special config that I can think of.

**Comment by guilleiguaran** [comment]
@renchap are you using Action Cable? `ws://localhost:3000` should be set for Action Cable (see https://github.com/rails/rails/issues/31309)

I've tested in an app and looks like we need to whitelist `http://localhost:3035` and `ws://localhost:3035` if `webpack-dev-server` is running.

**Comment by gauravtiwari** [comment]
>  dev server requires allowing ws://localhost:3035 and http://localhost:3035 as connect-src

headers options is now configurable from webpacker.yml so we can update it with CSP headers.

**Comment by guilleiguaran** [comment]
@gauravtiwari I'm going to test it and report results back

**Comment by gauravtiwari** [comment]
> Research about Angular and CSP, Done: AngularJS tries to autodetect if CSP is blocking dynamic code creation from strings (e.g., unsafe-eval not specified in CSP header) and automatically deactivates this feature. reference

@guilleiguaran Don't think it applies for angular 4

**Comment by gauravtiwari** [comment]
All examples work with: 

> p.script_src  :self, :https, :unsafe_eval

This is needed for angular

```rb
# Define an application-wide content security policy
# For further information see the following documentation
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

Rails.application.config.content_security_policy do |p|
  p.default_src :self, :https
  p.font_src    :self, :https, :data
  p.img_src     :self, :https, :data
  p.object_src  :none
  p.script_src  :self, :https, :unsafe_eval
  p.style_src   :self, :https, :unsafe_inline
  p.connect_src :self, :https, 'http://localhost:3035', 'ws://localhost:3035'

  # Specify URI for violation reports
  # p.report_uri "/csp-violation-report-endpoint"
end

# Report CSP violations to a specified URI
# For further information see the following documentation:
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only
# Rails.application.config.content_security_policy_report_only = true

```

```yml
    # webpacker.yml
    headers:
      'Access-Control-Allow-Origin': '*'
      'Content-Security-Policy': "script-src 'self' 'unsafe-eval'; connect-src 'self' ws://localhost:3035 http://localhost:3035"
      'X-Content-Security-Policy': "script-src 'self' 'unsafe-eval'; connect-src 'self' ws://localhost:3035 http://localhost:3035"
      'X-WebKit-CSP': "script-src 'self' 'unsafe-eval'; connect-src 'self' ws://localhost:3035 http://localhost:3035"
```
