### ISSUE TITLE
Theme JS files are not working with webpacker 3 + react + rails 5.1.4

### ISSUE THREAD

**Issue by charusat09** [rails/webpacker#1060]
I have downloaded one theme and wanted to integrate with Rails + react using webpacker gem. I am able to load CSS files of the theme to my react component in new application but JS files are not working i.e. scrolling is not working and contact me form validations are also not working. [Demo Site.](https://react-webpacker-rails.herokuapp.com/)

**app/views/layouts/application.html.erb**
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Optics</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'stylesheets/style' %>
    <%= stylesheet_pack_tag 'stylesheets/prettyPhoto' %>
    <%= stylesheet_pack_tag 'stylesheets/public' %>
  </head>
  <body>
    <%= javascript_pack_tag 'app' %>
  </body>
</html>
```

**app/javascript/packs/app.js**
```
import Modernizr from 'modernizr';
import React from 'react';
import ReactDOM from 'react-dom';
import WelcomePage from './components/welcomes/WelcomePage';
import "jquery";
import "bootstrap";
import "SmoothScroll";
import "jquery.prettyPhoto";
import "jquery.isotope.js";
import "jqBootstrapValidation";
import "contact_me";
import "main";

document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(
    <WelcomePage/>,
    document.body.appendChild(document.createElement('div')),
  )
})
```

**config/webpack/environment.js**
```
const { environment } = require('@rails/webpacker')

const webpack = require('webpack')

environment.plugins.set('Provide',  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    jquery: 'jquery',
    bootstrap: 'bootstrap/dist/js/bootstrap'
  })
)

const config = environment.toWebpackConfig()

config.resolve.alias = {
  $: 'jquery',
  jQuery: 'jquery',
  jquery: 'jquery',
  bootstrap: 'bootstrap/dist/js/bootstrap'
}
module.exports = environment
```
**config/webpack/development.js**
```
const merge = require('webpack-merge')
const environment = require('./environment')
const customConfig = require('./custom')

module.exports = merge(environment.toWebpackConfig(), customConfig)

```

**config/webpacker.yml**
```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  resolved_paths: ['app/javascript/packs/scripts']

  cache_manifest: false

  extensions:
    - .erb
    - .js
    - .jsx
    - .css
    - .png
    - .jpeg

development:
  <<: *default
  compile: true

  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false

production:
  <<: *default
  compile: false
  cache_manifest: true
```

**config/webpack/custom.js**
```
const path = require('path');

module.exports = {
  module: {
    rules: [
      {
        test: /\.modernizrrc.js$/,
        use: [ 'modernizr-loader' ]
      },
      {
        test: /\.modernizrrc(\.json)?$/,
        use: [ 'modernizr-loader', 'json-loader' ]
      }
    ]
  },
  resolve: {
    alias: {
      modernizr$: path.resolve(__dirname, "../../app/javascript/packs/.modernizrrc")
    }
  }
}
```

I have tried so many options but not get any solution.

Thanks in advance :-)
