### ISSUE TITLE
Inject ASSET_HOST in runtime, instead of compile time

### ISSUE THREAD

**Issue by simoniong** [rails/webpacker#1080]
Hi, all:

I am trying to migrate my whole asset from asset pipeline into webpack.
I have a issue while using CDN with webpacker, which do not happen in asset pipeline.

This is one of my scss file
``` scss
.header-content {
  background: url('../images/background.png') repeat center center;
}
```

while compile asset, I was using a `staging` env, which is fine, one of env variable is ASSET_HOST or WEBPACK_ASSET_HOST in latest master branch, which point to my staging CDN. and it compile to:

``` css
.header-content {
  background: url(https://staging-cdnhost.com/packs/images/background-9a30e6c6c75344e5bd217bbe9720ef3e.png) repeat center center;
}
```

Everything is correct here, but can we compile to a relative path so that we can inject ASSET_PATH within rails system in run time?

BTW: I have a use case here: my app is building within a docker image and I only build images once for both staging & production, so while building this image, and run `assets:precompile`, `RAILS_ENV` is point to `production`. this is working as asset pipeline only refer to `config.action_controller.asset_host` for CDN in different env, but in `webpacker`, seems CDN host  is injected in compile time, and can not changed in run time.

Is there anyway to change the behaviour?
