### ISSUE TITLE
asset paths inside assets when deploying to sub-url

### ISSUE THREAD

**Issue by ipmsteven** [rails/webpacker#1106]
#### Problem 
Asset paths inside assets when deploying to sub-URI have issue when resolving to right url

#### Example
When app is mounted under `/portal`, having a component like `Logo` below:

```javascript
import BookLogo from '../images/book_logo.jpg';

 export class Logo extends Component {
    render(){
        return (
          ...
          <img src={BookLogo} />
          ...
        )
    } 
}
```
The correct path `/portal/assets/packs/images/book_logo.jpg` is expected but a wrong path `/assets/packs/images/book_logo.jpg` is generated for src of img on production environment.

#### Question
Is there a config I can pass like how asset pipeline does by using `relative_url_root`?
#### Reference
https://github.com/rails/rails/pull/3946

**Comment by gauravtiwari** [comment]
@ipmsteven What happens if you set public output path as: 

```js
__webpack_public_path__ = `/portal/packs`
```

```jsx
__webpack_public_path__ = `/portal/packs`
import BookLogo from '../images/book_logo.jpg';

 export class Logo extends Component {
    render(){
        return (
          ...
          <img src={BookLogo} />
          ...
        )
    } 
}
```

And then build and deploy to production?

**Comment by ipmsteven** [comment]
Hi @gauravtiwari , Thanks for you reply, that would work but have some manual work involved.

since `webpacker:compile` is part of asset pipeline, could we let `webpacker:compile`
respect the `relative_url_root` setting from rails?

**Comment by bingneef** [comment]
If `__webpack_public_path__ = '/portal/packs'` does not work, make sure to have at least webpacker 3.2.0 in your package.json (`yarn add @rails/webpacker`), I stared at this for ages since I only updated the gem, not the NPM version.

**Comment by linstantnoodles** [comment]
@ipmsteven Have you tried configuring your `webpacker.yml` file to have
`public_output_path: portal/packs` so that all of your pack assets go to `portal/`?

**Comment by ipmsteven** [comment]
@linstantnoodles yes, that could work, but it's not a good solution for my use case.

In my situation `portal` is a configurable value,  it is stored in a configuration file and different environments has different settings.

Say for dev: it's '/', for test: it's '/test', for stage, it's '/blah', etc.
but no matter what's environments you are in, it's should always the same with relative_url_root(where the app is mounted to)
That's the reason I create this PR  https://github.com/rails/webpacker/pull/1236

Does that make sense to you @linstantnoodles ?

**Comment by wpp** [comment]
Hmm, I've tried `__webpack_public_path__ = '/portal/packs'` (webpacker 3.2.1 as suggested) but the url is still missing `/portal`. @bingneef anything else you had to configure?

**Comment by brunoOSI** [comment]
@linstantnoodles, that locks your generated assets with a given configuration. If you have to deploy the same app to a different path you are in trouble. 

@ipmsteven I 👍 your PR, that is awesome and so needed.

**Comment by bingneef** [comment]
@wpp I believe not, what does your webpacker.yml look like?

**Comment by wpp** [comment]
I think it's the default configuration.

```yaml
default: &default                                                               
  source_path: app/javascript                                                   
  source_entry_path: packs                                                      
  public_output_path: packs                                                                    
  # cache_path: tmp/cache/webpacker                                             
                                                                                
  # Additional paths webpack should lookup modules                              
  # ['app/assets', 'engine/foo/app/assets']                                     
  resolved_paths: ['app/assets']                                                
                                                                                
  # Reload manifest.json on all requests so we reload latest compiled packs     
  cache_manifest: false                                                         
                                                                                
  extensions:                                                                   
    - *omitted for brevity*
```
