### ISSUE TITLE
Object spread does not work

### ISSUE THREAD

**Issue by rhazegh** [rails/webpacker#1111]
Browser console shows the following error:
```
RenderUpgradeProduct.js:11 Uncaught Error: Module build failed: SyntaxError: Unexpected token (77:61)

  75 |                                                 <Product
  76 |                                                     key={index}
> 77 |                                                     product={...product}
     |                                                              ^
  78 |                                                 />
  79 |                                             )}
  80 |                                         </div>
```

- Webpack: 3.1.1
- Rails 4.2.10
- Ruby: 2.3.5
- RVM: 1.29.3
- Node: v8.9.1

`.babelrc`
```json
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": true
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}
```

`package.json`
```json
{
  "dependencies": {
    "@rails/webpacker": "^3.1.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "coffeescript": "1.12.7",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-modal": "^3.1.8"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.9.7"
  }
}
```

`config/webpacker.yaml`
```yaml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```

`config/webpack/environment.js`
```
const { environment } = require('@rails/webpacker');
module.exports = environment;
```

`config/webpack/development.js`
```
const environment = require('./environment')
module.exports = environment.toWebpackConfig()
```
