### ISSUE TITLE
Compiling assets with Elm fails on Heroku

### ISSUE THREAD

**Issue by deepj** [rails/webpacker#1126]
Getting this on Heroku:

```
remote:        Webpacker is installed 🎉 🍰
remote:        Using /tmp/build_66bd10be621593eefc25db68d303a65e/config/webpacker.yml file for setting up webpack paths
remote:        Compiling…
remote:        Compilation failed:
remote:        Hash: f2d4ee7244c526e7fc57
remote:        Version: webpack 3.5.4
remote:        Time: 591ms
remote:        Asset       Size  Chunks             Chunk Names
remote:        hello_elm-1240c682b3dc61c15958.js    1.06 kB       0  [emitted]  hello_elm
remote:        application-7c650703a2a64e2436f0.js  547 bytes       1  [emitted]  application
remote:        hello_elm-1240c682b3dc61c15958.js.map    7.89 kB       0  [emitted]  hello_elm
remote:        application-7c650703a2a64e2436f0.js.map    6.35 kB       1  [emitted]  application
remote:        hello_elm-1240c682b3dc61c15958.js.gz  635 bytes          [emitted]
remote:        application-7c650703a2a64e2436f0.js.gz  343 bytes          [emitted]
remote:        manifest.json  274 bytes          [emitted]
remote:        [0] ./app/javascript/packs/application.js 517 bytes {1} [built]
remote:        [1] ./app/javascript/packs/hello_elm.js 400 bytes {0} [built]
remote:        [2] ./app/javascript/Main.elm 267 bytes {0} [built] [failed] [1 error]
remote:        ERROR in ./app/javascript/Main.elm
remote:        Module parse failed: /tmp/build_66bd10be621593eefc25db68d303a65e/app/javascript/Main.elm Unexpected token (1:7)
remote:        You may need an appropriate loader to handle this file type.
remote:        | module Main exposing (..)
remote:        |
remote:        | import Html exposing (Html, h1, text)
remote:        @ ./app/javascript/packs/hello_elm.js 5:0-26
remote:  !
remote:  !     Precompiling assets failed.
```

`environment.js`:

```javascript
const { environment } = require('@rails/webpacker')
const elm =  require('./loaders/elm')

environment.loaders.append('elm', elm)
module.exports = environment
```

`elm.js`

```javascript
const { resolve } = require('path')

const isProduction = process.env.NODE_ENV === 'production'
const elmSource = resolve(process.cwd())
const elmMake = `${elmSource}/node_modules/.bin/elm-make`

const elmDefaultOptions = { cwd: elmSource, pathToMake: elmMake }
const developmentOptions = Object.assign(elmDefaultOptions, {
  verbose: true,
  warn: true,
  debug: true
})

const elmWebpackLoader = {
  loader: 'elm-webpack-loader',
  options: isProduction ? elmDefaultOptions : developmentOptions
}

module.exports = {
  test: /\.elm(\.erb)?$/,
  exclude: [/elm-stuff/, /node_modules/],
  use: isProduction ? [elmWebpackLoader] : [{ loader: 'elm-hot-loader' }, elmWebpackLoader]
}
```

**Versions**:
- webpacker 3.2.0
- rails 5.1.4

Everything updated, just `rails webpacker:install && rails webpacker:install:elm`. When I run `rails assets:precompile` on my local machine, no issue is occurred.

**Comment by silaspedrosa** [comment]
I'm having the exact same issue and I'm **not** using heroku.

**Comment by deepj** [comment]
@schneems Hello, is it possible to check this? Elm compilation with Webpacker doesn't work at all.

**Comment by gauravtiwari** [comment]
@deepj @silaspedrosa Going to take a look at this now. Seems to be compiling fine last time. Are you using nodejs buildpack?

**Comment by deepj** [comment]
@gauravtiwari Hi, yes, we use the nodejs buildpack.

![screen shot 2017-12-22 at 18 21 47](https://user-images.githubusercontent.com/33736/34306767-23626770-e745-11e7-8067-bc2b87842b1b.png)

**Comment by gauravtiwari** [comment]
Great thanks and the yarn version is latest?

**Comment by gauravtiwari** [comment]
Will try to deploy one now and report back.

**Comment by deepj** [comment]
@gauravtiwari 
Here is the output of the whole deploy:

https://gist.github.com/deepj/02e271f61dd840cdafc310bb433a1d9a

Just a note, what's worth to mention, we use still Rails assets for JS and CSS. We want to migrate everything under `webpack`. `webpacker` will be used only for Elm components for now.

**Comment by deepj** [comment]
It seems the problem lies in webpack configuration for production environment. The above mentioned error can be easily reproducible using `RAILS_ENV=production rails assets:precompile` on a local machine.

**Comment by gauravtiwari** [comment]
@deepj Just posted this example with elm app: https://github.com/gauravtiwari/webpacker-elm

Seems to deploy fine: https://aqueous-tor-80299.herokuapp.com/

**Comment by deepj** [comment]
This is really weird. If I run `rails webpacker:install` and `rails webpacker:install:elm`. After that, my `config/webpacker.yml` looks the following:

```yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .elm
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```

But I copy your `config/webpacker.yml` -> https://github.com/gauravtiwari/webpacker-elm/blob/master/config/webpacker.yml then it starts working.

The diff looks this way

![screen shot 2017-12-22 at 19 34 31](https://user-images.githubusercontent.com/33736/34308848-7a9ad22a-e74f-11e7-86cc-82fbc793fc44.png)
