### ISSUE TITLE
Add support for "--watch-poll" webpack-dev-server flag

### ISSUE THREAD

**Issue by colinrcummings** [rails/webpacker#1159]
The file change detection isn't working in vagrant on a Windows host. Adding the "--watch-poll" flag to the command should solve the issue, but it's not currently available in `config/webpacker.yml`. Could it be added like this:
```
dev_server:
    ...
    watch_poll: false
```
Default to false, but toggling to true would apply the flag.

See:
https://github.com/webpack/webpack-dev-server/issues/155#issuecomment-159140735
https://github.com/webpack/webpack-dev-server/issues/324#issuecomment-241204865
http://stackoverflow.com/a/34937378

**Comment by renchap** [comment]
You can add it yourself as an argument: `./bin/webpack-dev-server --watch-poll`
This is better to do it on the computers that need this flag rather than in your config for all users.

**Comment by colinrcummings** [comment]
@renchap, I tried that. After the initial output, I see `[HMR] Waiting for update signal from WDS...` in the client console but WDS never rebuilds the bundle after file changes.

**Comment by colinrcummings** [comment]
I'm using this in the context of `react_on_rails`. 

My `config/webpacker.yml`:

```
dev_server:
    https: false
    host: 0.0.0.0
    port: 3035
    public: localhost:3035
    hmr: true
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/
```

My `Procfile.dev-server`, which I start with `$ foreman start -f Procfile.dev-server`:

```
web: rails s -p 3000 -b 0.0.0.0

client: sh -c 'rm -rf public/packs/* || true && bundle exec rake react_on_rails:locale && bin/webpack-dev-server --watch-poll'
```

My `Vagrantfile`:

```
Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.network 'forwarded_port', guest: 3000, host: 3000
  config.vm.network 'forwarded_port', guest: 3035, host: 3035
  config.vm.network 'forwarded_port', guest: 5432, host: 5432

  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder ".", "/vagrant", nfs: true,
    mount_options: %w{nolock,vers=3,udp,noatime,actimeo=1}

  config.vm.provider 'virtualbox' do |v|
    host = RbConfig::CONFIG['host_os']
    if host =~ /darwin/
      mem = `sysctl -n hw.memsize`.to_i / 1024
    elsif host =~ /linux/
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i
    elsif host =~ /mswin|mingw|cygwin/
      mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
    end

    mem = mem / 1024 / 4
    v.customize ["modifyvm", :id, "--memory", mem]
  end

  config.vm.provision 'shell', privileged: false, path: 'vagrant/provision_script.sh'
end
```
