### ISSUE TITLE
Conditional PostCSS plugins

### ISSUE THREAD

**Issue by Superpencil** [rails/webpacker#1220]
I'm attempting to generate an rtl version of my main css file. I've found a PostCSS plugin called rtlcss that produces the output I need, my config looks like this:
```yml
# .postcssrc.yml

plugins:
  postcss-import: {}
  postcss-cssnext: {}
  rtlcss: {}
```

However, I only want to use rtlcss on a single file, not all. 
Would it be possible to have a different postcss config for a single file, like shown in https://github.com/postcss/postcss-loader#config-cascade ?

**Desired Input**
```scss
// application.scss

body {
  text-align: left;
}
```
```scss
// application.rtl.scss

@import 'application.scss'
```

**Desired Output**
```css
/* application.css */

body {
  text-align: left;
}
```
```css
/* application.rtl.css */

body {
  text-align: right;
}
```

Any help pointing in the right direction is much appreciated ✌🏻
