### ISSUE TITLE
webpack-dev-server on custom environment

### ISSUE THREAD

**Issue by Jaroost** [rails/webpacker#1291]
I try to use the `webpack-dev-server` script on my custom environment `home`.

I added a new configuration in `webpacker.yml`

```
home:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: true
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/

```
Then I start the `ruby .\bin\webpack-dev-server` (I am on Windows10)

The script compiles on demand works and the server is up and running at https://localhost:3035

But when I make changes, the navigator doesn't refresh automatically and rails server compile instead of the on demande script.

Do i miss something?

PS: In development environment, all works just fine
