### ISSUE TITLE
webpack-dev-server hot reload not working on cloud9

### ISSUE THREAD

**Issue by reckerswartz** [rails/webpacker#1296]
As previously discussed in issue #176  . I am having trouble making web pack work with Rails in my development environment, which is Cloud9.
My Environment:
Gems included by the bundle:
(Few are Below)
  * bundler (1.16.1)
  * coffee-rails (4.2.2)
  * nokogiri (1.8.2)
  * puma (3.11.2)
  * rails (5.2.0.rc1)
  * turbolinks (5.1.0)
  * turbolinks-source (5.1.0)
  * webpacker (3.2.2)
  * websocket-driver (0.7.0)
  * websocket-extensions (0.1.3)

Package Json
```json
{
  "name": "******-dev",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "^3.2.2",
    "vue": "^2.5.13",
    "vue-loader": "^14.1.1",
    "vue-template-compiler": "^2.5.13"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.11.1"
  }
}

```
Changed the ```development.dev_server``` entry ```config/webpacker.yml``` file into
```yml
dev_server:
    https: true
    host: localhost
    port: 3035
    public: your-workspace-name-yourusername.c9users.io:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: false
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/
```
after running ```webpack-dev-server``` live changes cannot be seen without reload.
When ```Inline``` sets to ```true``` then i have error
![capture](https://user-images.githubusercontent.com/16918568/36678350-826bd632-1b36-11e8-98b7-56fdbc9b29bd.PNG)

**Comment by kriera** [comment]
Hi there, what line are you using to execute the webpack-dev-server? 

I've one similar issue trying to execute webpack dev

constantly getting those errors, 
webpack-dev-server/bin/webpack-dev-server.js:405
    throw e;

i've tried 

webpack-dev-server --host localhost --port 8081

webpack-dev-server --host $IP --port $PORT

webpack-dev-server --public $C9_HOSTNAME:8081 

if i put the url of the server xxxxxx.xxxx.cloud9.us.. etc on the host: and public: url:port 

i get 

bind(2) for "xxxxxx.xxxx.cloud9.us...com" port 8081

not really sure what to check more, rails s is not running so port is free, so maybe you can throw some light on that :)

thanks!

**Comment by reckerswartz** [comment]
@kriera just bin/webpack-dev-server
to run webpacker dev server

**Comment by kingpalethe** [comment]
I gave up trying to get HMR working on Cloud9, and I'm actually struggling to turn HMR **off** completely.
 
I am following these directions https://github.com/rails/webpacker/blob/master/docs/cloud9.md.

The current problem I am having is that my chrome console seems to still be polling webpacker, and is showing this error message:

```
Failed to load https://xxxxxx.c9users.io:8082/sockjs-node/info?t=1523398135503: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://xxxxx.c9users.io' is therefore not allowed access. The response had HTTP status code 503.
```
This message appears about every 3 seconds, so I am assuming this is a problem with HMR.

This is the bash script I am using to start rails and webpacker

```
# https://github.com/rails/webpacker/blob/master/docs/cloud9.md

# Immediately exit script on first error
set -e -o pipefail

# APP_ROOT_FOLDER="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
# cd "${APP_ROOT_FOLDER}"

if [ -n "${C9_USER}" ]; then
  # We are in a Cloud9 machine

  # Make sure that Postgres is running
  sudo service postgresql status || sudo service postgresql start

  # Adapt the configuration of the webpack-dev-server
  export APP_DOMAIN="${C9_HOSTNAME}"
  export RAILS_SERVER_BINDING='0.0.0.0'
  export RAILS_SERVER_PORT='8080'
  export WEBPACKER_DEV_SERVER_PORT='8082'
  export WEBPACKER_DEV_SERVER_HTTPS='true'
  export WEBPACKER_DEV_SERVER_HOST="localhost"
  export WEBPACKER_DEV_SERVER_PUBLIC="${C9_HOSTNAME}:${WEBPACKER_DEV_SERVER_PORT}"
  export WEBPACKER_DEV_SERVER_HMR='false'
  export WEBPACKER_DEV_SERVER_INLINE='false'
  export WEBPACKER_DEV_SERVER_OVERLAY='true'
  export WEBPACKER_DEV_SERVER_DISABLE_HOST_CHECK='true'
  export WEBPACKER_DEV_SERVER_USE_LOCAL_IP='false'
fi

foreman start -f Procfile.dev
```

This is my `Procfile.dev`

```
web: ./bin/rails server -b ${RAILS_SERVER_BINDING:-localhost} -p ${RAILS_SERVER_PORT:-3000}
webpacker: ./bin/webpack-dev-server
```

This is the relevant part of my `Webpacker.yml`
```
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: false
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/
```

This is the relevant part of my Gemfile


```
gem 'rails', '~> 5.2'
ruby '2.5.1'
gem 'webpacker'
```

This is my `package.json`

```

{
  "name": "factbar",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "3.4",
    "axios": "^0.18.0",
    "babel-preset-react": "^6.24.1",
    "bignumber.js": "^6.0.0",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.5",
    "math.js": "^1.1.43",
    "prop-types": "^15.6.1",
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-image-resizer": "^1.3.0",
    "react-web3": "^0.4.5",
    "truffle": "^4.1.5",
    "truffle-contract": "^3.0.4",
    "web3": "^0.20.0"
  },
  "devDependencies": {
    "babel-plugin-transform-class-properties": "^6.24.1",
    "webpack-cli": "^2.0.14",
    "webpack-dev-server": "2.11.2"
  }
}
```
