### ISSUE TITLE
Launching Webpacker to AWS CodePipeline & CodeBuild

### ISSUE THREAD

**Issue by mujuni88** [rails/webpacker#1314]
I'm new to the ruby world and I was wondering if there was a simpler way to run Webpacker on AWS CodeBuild without having to run all the commands on my `buildspec.yml`

```
version: 0.2

phases:
  install:
    commands:
      - echo get the latest bundler
      - gem install bundler
      - echo Installing Ruby dependencies
      - bundle install --deployment
  pre_build:
    commands:
      - echo Installing and setting up webpack with yarn
      - bundle exec rake webpacker:install
      - echo Verifying if Node.js is installed
      - bundle exec rake webpacker:check_node
      - echo Verifying if yarn is installed
      - bundle exec rake webpacker:check_yarn
      - echo Installing all Javascript dependencies as specified via Yarn
      - bundle exec rake webpacker:yarn_install
  build:
    commands:
      - echo Build started on `date`
      - echo Testing
      - yarn test
      - echo Checking if Webpack compiles
      - bundle exec rake webpacker:compile
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
```
