### ISSUE TITLE
On Mac High Serra, the webpack-dev-server process is killed intermittently 

### ISSUE THREAD

**Issue by loganfreeman** [rails/webpacker#1367]
The following is an example of the console message when the `webpack-dev-server` gets killed.

```
 10% building modules 5/5 modules 0 active
Project is running at http://localhost:3035/
webpack output is served from /packs/
Content not from webpack is served from /erc/public/packs
404s will fallback to /index.html
 10% building modules 7/15 modules 8 active .../webpack/hot nonrecursive /^\.\/log$/(node:2999) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 95% emittingKilled
```

I have `config\webpack\development.js` set up like the folllowing:

const environment = require('./environment');

```javascript
const devConfig = environment.toWebpackConfig();
devConfig.devServer.watchOptions = {
  ignored: /node_modules/,
  aggregateTimeout: 300,
  poll: 500,
};
// devConfig.devServer.inline = false;
// devConfig.devServer.hot = false;
module.exports = devConfig;
```

**Comment by rossta** [comment]
@loganfreeman This sounds like an issue with memory constraints. Could you try getting some info about memory usage when this happens. Also, it would really help to share info about your setup: Webpacker gem version, @rails/webacker package version, node version, Rails version, etc.

**Comment by loganfreeman** [comment]
webpacker version

```
    webpacker (3.0.2)
      activesupport (>= 4.2)
      rack-proxy (>= 0.6.1)
      railties (>= 4.2)
```

@rails/webpacker version

```
  "name": "@rails/webpacker",
  "version": "3.0.2",
```

node version

```
node -v
v6.13.0
```

rails version

```
rails -v
Rails 4.2.7.1
```

Puma.rb

```
# Specifies the `environment` that Puma will run in.
rails_env = ENV.fetch("RAILS_ENV", "development")
environment rails_env

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
port ENV.fetch("PORT", 3000).to_i

# Change to match your CPU core count
workers ENV.fetch("WORKER_PROCESSES", 1).to_i

# Min and Max threads per worker
threads_count = ENV.fetch("RAILS_MAX_THREADS", 2).to_i
threads threads_count, threads_count

app_dir = "/erc"
directory app_dir

# Set master PID and state locations
pidfile "#{app_dir}/tmp/pids/puma.pid"
state_path "#{app_dir}/tmp/pids/puma.state"
activate_control_app

on_worker_boot do
  require "erb"
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load(ERB.new(File.read("#{app_dir}/config/database.yml")).result)[rails_env])
end
```

docker-compose

```
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
    container_name: erc
    command: bash
    links:
      - mysql
      - redis
      - solr
      - solrtest
      - memcached
    volumes:
      - .:/erc
    ports:
      - 3000:3000
      - 3035:3035
    env_file:
      - .env
    tty: true
    stdin_open: true
```
