### ISSUE TITLE
CSS Modules :global

### ISSUE THREAD

**Issue by skrobek** [rails/webpacker#1369]
Hi, recently we have updated our version of webpacker. Following docs we add a configuration for CSS modules:

```js
// CSS loaders
const myCssLoaderOptions = {
  modules: true,
  importLoaders: 1,
  sourceMap: true,
  localIdentName: '[name]__[local]___[hash:base64:5]'
};

const CSSLoader = environment
  .loaders
  .get('css')
  .use
  .find(el => el.loader === 'css-loader');

CSSLoader.options = merge(CSSLoader.options, myCssLoaderOptions);
```

Unfortunately, not everything is ok. We using some external libraries for a component i.e Dropdown, so we need to style them via `:global` from CSS modules library. The problem is that styles are not applied to the class via the following code:
```css
  :global {
    .Dropdown-control {
      padding: 0.1rem 1.25rem;
      padding-right: 2.5rem;
      border-radius: 0 0.1875rem 0.1875rem 0;
      height: 2.5rem;
    }

    .Dropdown-option {
      padding: 0.125rem 0.5rem;
    }
  }
```
Any ideas ?
