### ISSUE TITLE
SCSS loader issue, partial variables and mixins not working.

### ISSUE THREAD

**Issue by lmmendes** [rails/webpacker#1432]
Hi guys, sorry for this issue but I'm completely stuck.

I'm running a Rails v4.2.9 legacy app and migrating from sprockets to Rails webpacker v3.4.3.

I'm having the following issues:

```
 ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/packs/styles/peculiar/_sections.scss
    Module build failed:
        color: $blue-peculair;
              ^
          Undefined variable: "$blue-peculair".
          in /legacy-app/app/javascript/packs/styles/peculiar/_sections.scss (line 9, column 12)
```

And

```
ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/packs/styles/peculiar/_product_cards.scss
Module build failed:
    @include sans-serif-font;
            ^
      No mixin named sans-serif-font

Backtrace:
	stdin:3
      in /legacy-app/app/javascript/packs/styles/peculiar/_product_cards.scss (line 3, column 14)
Error:
    @include sans-serif-font;
            ^
      No mixin named sans-serif-font
```

It seems that the scss loader lost the scope of the loaded scss partials and their declared mixins and variables. Any clues?

Here goes the complete dump of my current settings:

The entrypoint is `app/javascript/packs/application.js` and in it's first line it calls:

```
import 'application.scss'
```

The the `application.scss`requires all `*.scss` nedeed files:

```
@import "styles/peculiar/mixins";

@import "styles/bootstrap-custom";

@import '~bootstrap/scss/bootstrap';

@import "~float-labels.js/src/float-labels";
@import "styles/float-labels-custom";

@import "styles/peculiar/base";
@import "styles/peculiar/forms";
@import "styles/peculiar/basket";
@import "styles/peculiar/search";
@import "styles/peculiar/product_description";
@import "styles/peculiar/registration";
@import "styles/peculiar/masterhead";
@import "styles/peculiar/navbar";
@import "styles/peculiar/sections";
@import "styles/peculiar/product_cards";
@import "styles/peculiar/footer";
@import "styles/peculiar/newsletter";
```

Here us the `app/javascript/packs` folder structure:

```
.
└── packs
    ├── ajax-loader.gif
    ├── application.js
    ├── application.scss
    ├── owl.video.play.png
    ├── stripe-payment-store.js
    ├── stripe-payments.js
    └── styles
        ├── _bootstrap-custom.scss
        ├── _float-labels-custom.scss
        └── peculiar
            ├── _base.scss
            ├── _basket.scss
            ├── _footer.scss
            ├── _forms.scss
            ├── _masterhead.scss
            ├── _mixins.scss
            ├── _navbar.scss
            ├── _newsletter.scss
            ├── _product_cards.scss
            ├── _product_description.scss
            ├── _registration.scss
            ├── _search.scss
            ├── _sections.scss
            ├── _stripe_payments.scss
            ├── ajax-loader.gif
            └── owl.video.play.png
````

My `webpacker.yml` has the following configuration:

```
development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: 0.0.0.0
    port: 3035
    # public: 3804902e.ngrok.io:443
    public: localhost
    hmr: false
    # Inline should be set to true if using HMR
    inline: false
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/
``` 

The `config/webpack/environment.js`:

```
const { environment } = require('@rails/webpacker')

const merge   = require('webpack-merge')
const webpack = require('webpack')

// See https://github.com/rails/webpacker/blob/master/docs/webpack.md#plugins

environment.plugins.prepend(
  'Provide',
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    jquery: 'jquery',
    'window.Tether': 'tether'
  })
)

const envConfig = module.exports = environment

const aliasConfig = module.exports = {
  resolve: {
    alias: {
      jquery: 'jquery/src/jquery'
    }
  }
}

// Le't merge all settings and return them
// module.exports = merge(envConfig.toWebpackConfig(), aliasConfig)
module.exports = merge(envConfig.toWebpackConfig(), aliasConfig)
```

**Comment by gauravtiwari** [comment]
@lmmendes The packs folder is only made for webpack entries. Please, could you move out the styles and images out of packs folder and see if that helps? 

```yml
styles:
  - all css files
images
 - all images
packs:
 - application.js # imports application.css
```
