### ISSUE TITLE
Using webpacker on AWS Cloud 9 (i.e. aws.amazon.com/cloud9 not c9.io)

### ISSUE THREAD

**Issue by michaelqz** [rails/webpacker#1553]
Hi, I've been trying to migrate my workspace from Cloud 9 to AWS Cloud 9 but the js files do not load when trying to preview the app in chrome.

I've tried to use the the guide kindly written up at [cloud9.md](https://github.com/rails/webpacker/blob/master/docs/cloud9.md), but without success.

I've tried the following `webpacker.yml` setting, but the file does not load as chrome is looking for the js pack files in https://localhost, I guess as expected.
```
  dev_server:
    https: true
    host: localhost
    port: 8082
    public: {redacted hash}.vfs.cloud9.ap-southeast-1.amazonaws.com:8082
    hmr: false
    inline: false
    overlay: true
    disable_host_check: true
    use_local_ip: false
```

I then tried the following `webpacker.yml` settings, also without success (in fact an error message comes up, error message says `Error: listen EADDRNOTAVAIL {ip address}:8082`).

```
dev_server:
    https: true
    host: {redacted hash}.vfs.cloud9.ap-southeast-1.amazonaws.com
    port: 8082
    public: {redacted hash}.vfs.cloud9.ap-southeast-1.amazonaws.com:8082
    hmr: false
    inline: false
    overlay: true
    disable_host_check: true
    use_local_ip: false
```
Does anyone know how to get webpacker for a Ruby on Rails app working on AWS Cloud 9?
