### ISSUE TITLE
Capistrano deploy fails randomly on webpacker compile

### ISSUE THREAD

**Issue by gregblass** [rails/webpacker#1557]
Hey there! I'm using Rails 5.2 and webpacker 3.5.3, and deploying my app using Capistrano. I used to have more or less a fail-proof method of deploying, until I introduced webpacker. I'd say about once every 10 deploys or so, it will hang for about a minute when webpacker hits the 'Compiling...' step - then fail without an error message.

If I try to deploy again after that, it works fine. I'd probably just be OK dealing with this - however, during the 60 or so seconds that its on that compiling step, the website becomes unresponsive.

Any insight as to what could possibly be happening would be greatly appreciated because I have no idea where to even start (I'm super new with webpacker).

Here's my webpacker.yml file (I don't believe I've manually touched it):

```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```
