### ISSUE TITLE
Unable to bundle css from imported scss in production

### ISSUE THREAD

**Issue by freezepl** [rails/webpacker#1635]
Hi!
We are using webpacker default configuration and importing scss files in jsx like this:
`import './errors-popup.scss';` 

I am unable to get production compiled scss files under one `applicaction-hash.css` although css are in the manifest.json. After deploying site is without styles.

Should I import every single scss file in application.scss and then this file in application.js?

```
app/javascript
├── components
│   ├── setup-container
│   │   ├── configuration-container.jsx
│   │   ├── form-step
│   │   │   ├── form-step.jsx
│   │   │   └── form-step.scss
│   │   ├── product-mapping-step
│   │   │   ├── product-mapping-step.jsx
│   │   │   └── row.jsx
│   │   └── settings-step
│   │       └── settings-step.jsx
│   └── shared
│       ├── errors-popup
│       │   ├── errors-popup.jsx
│       │   └── errors-popup.scss
│       ├── link-failure
│       │   └── link-failure.jsx
│       └── setup-navbar
│           ├── setup-navbar.jsx
│           ├── setup-navbar.scss
│           ├── setup-step.jsx
│           └── setup-step.scss
├── packs
│   ├── application.js
│   ├── setup-container.js
│   └── shared.js
└── stylesheets
    ├── application.scss
    └── shared
        ├── _colors.scss
        └── _fonts.scss
```

production.js
```
process.env.NODE_ENV = process.env.NODE_ENV || 'production';
const environment = require('./environment');
environment.loaders.get('sass').use.find(item => item.loader === 'sass-loader').options.sourceMapContents = false;
module.exports = environment.toWebpackConfig();
```
environment.js
```
const { environment } = require('@rails/webpacker')
module.exports = environment
```
webpacker.yml
```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  resolved_paths: []
  cache_manifest: false
  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  dev_server:
    hmr: false
development:
  <<: *default
  compile: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/
test:
  <<: *default
  compile: true
  public_output_path: packs-test
production:
  <<: *default
  compile: false
  cache_manifest: true
staging:
  <<: *default
  compile: false
  cache_manifest: true
```
packs/application.js
```
import '../stylesheets/application.scss';
```
packs/setup-container.js
```
import WebpackerReact from 'webpacker-react';
import ConfigurationContainer from '../components/setup-container/configuration-container';
WebpackerReact.setup({ ConfigurationContainer });
```
application.html.erb
```
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'setup-container' %>
    <%= javascript_pack_tag 'shared' %>
```

There is no clear docs about it. I would like to remove maps and have all under two files. JS and CSS.
Thanks
