### ISSUE TITLE
Webpacker 3.5 issue with resolve-url-loader for PRODUCTION

### ISSUE THREAD

**Issue by HectorLS** [rails/webpacker#1731]
**Ruby**: 2.5.1
**Rails**: 5.2.1
**Bundle**:  >1.3.0
**Webpacker gem**: 3.5.5

Hi, i am using webpacker and **everything works for development**, but when i tried to compile **for production i got this error**

```shell
ERROR in Entry module not found: Error: Can't resolve 'resolve-url-loader' in
'/home/deploy/rails/251/project-name/releases/20181004142122'
```

I do not understand, what _Can't resolve_ means here and what can i do to fix it.
That package is a webpacker dependency to be able to find the file paths.

**My Setup**

**.babelrc**
```json
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }]
  ]
}
````

**webpacker.yml**
```yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/frontend
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```

webpack/**environment.js**
```js
const { environment } = require('@rails/webpacker');
const webpack         = require('webpack');


environment.plugins.get('ExtractText'); 
environment.plugins.append('Provide',  new webpack.ProvidePlugin({
    $     : 'jquery',
    jQuery: 'jquery',
    jquery: 'jquery',
    Popper: ['popper.js', 'default']
  })
);


environment.loaders.get('sass').use.splice(-1, 0, {
  loader: 'resolve-url-loader',
  options: {
    attempts: 1
  }
});

// export the updated config
module.exports = environment
```
