### ISSUE TITLE
javascript_pack_tag pointing to wrong location

### ISSUE THREAD

**Issue by nhbain** [rails/webpacker#1784]
I added webpacker to my rails 5 project in order to utilize a few node modules that are necessary for some of the functionality. I had no issue getting things up and running locally, but when I deploy to production (I'm using Amazon Elastic Beanstalk), the javascript_pack_tag points to the wrong location. For example, at this test deployment (http://production-test.us-west-2.elasticbeanstalk.com), the url generated by the tag is (http://production-test.us-west-2.elasticbeanstalk.com/packs/process_landsat-18191562216c726dbe6a.js) when it should be (http://production-test.us-west-2.elasticbeanstalk.com/public/packs/process_landsat-18191562216c726dbe6a.js). 

I've tried changing the public output path in webpacker.yml, but it never looks within the public folder regardless of any changes I make. The rest of the url is updated correctly though. Considering this, I thought the issue might reside with the nginx config. So, I started modifying it but still haven't been able to correct the issue. I'm sure it's not too complicated, but I can't seem to figure it out. Does anyone have any ideas?
 
My current webpacker.yml setup and nginx config files are shown below. 

**webpacker.yml**

```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  resolved_paths: []

  cache_manifest: false

  extensions:
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/


test:
  <<: *default
  compile: true

  public_output_path: packs-test

production:
  <<: *default

  compile: false
  public_output_path: packs
  dist_dir: packs
  dist_path: public/packs
  cache_manifest: true

```

**nginx_proxy.config**

```
files:
  "/etc/nginx/conf.d/websockets.conf" :
    content: |

      server {
        location /packs/ {
          root /var/app/current/public;
        }
      }

container_commands:
  01restart_nginx:
    command: "service nginx restart"

```

**Comment by danielpowell4** [comment]
@nhbain Did you try changing this line in your webpacker.yml?

```yml
default: &default
  source_entry_path: packs
  public_output_path: packs # <-- I'D FIDDLE WITH THIS ONE, maybe /public/packs
```
