### ISSUE TITLE
TS2307: Cannot find module '../hello'

### ISSUE THREAD

**Issue by johansmitsnl** [rails/webpacker#1891]
I followed the guide https://github.com/rails/webpacker/blob/master/docs/typescript.md#typescript-with-vue-components but when running webpacker I get the error: `TS2307: Cannot find module '../hello'`

My files:
`app/javascript/packs/hello.ts`
```ts
import Vue from 'vue/dist/vue.esm'
import Hello from '../hello'
```

`app/javascript/hello.vue`
```vue
<template>
  <div id="app">
    <p>{{ message }}</p>
  </div>
</template>

<script lang="ts">
export default {
  data: function () {
    return {
      message: "Hello Vue!"
    }
  }
}
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
```

`config/webpack/loaders/typescript.js`
```js
module.exports = {
  test: /\.(ts|tsx)?(\.erb)?$/,
  use: [{
    loader: 'ts-loader',
    options: {
      appendTsSuffixTo: [/\.vue$/]
    }
  }]
};
```

```
$ bin/webpack-dev-server
Project is running at http://localhost:3035/
webpack output is served from /packs/
Content not from webpack is served from /home/johan/sources/ruby/crm/public/packs
404s will fallback to /index.html
Hash: 0f31a615183b87e006a6
Version: webpack 3.12.0
Time: 1349ms
                            Asset       Size  Chunks                    Chunk Names
    hello-bb7898e776dcb80b852a.js     331 kB       0  [emitted]  [big]  hello
hello-bb7898e776dcb80b852a.js.map     385 kB       0  [emitted]         hello
                    manifest.json  118 bytes          [emitted]         
   [2] multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/hello.ts 40 bytes {0} [built]
   [3] (webpack)-dev-server/client?http://localhost:3035 7.93 kB {0} [built]
   [4] ./node_modules/url/url.js 23.3 kB {0} [built]
   [7] ./node_modules/url/util.js 314 bytes {0} [built]
   [8] ./node_modules/querystring-es3/index.js 127 bytes {0} [built]
  [11] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [12] ./node_modules/ansi-regex/index.js 135 bytes {0} [built]
  [13] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
  [14] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
  [15] ./node_modules/sockjs-client/dist/sockjs.js 181 kB {0} [built]
  [16] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
  [18] ./node_modules/html-entities/index.js 231 bytes {0} [built]
  [21] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
  [23] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [25] ./app/javascript/packs/hello.ts 993 bytes {0} [built] [1 error]
    + 11 hidden modules

ERROR in ./app/javascript/packs/hello.ts
[tsl] ERROR in /home/johan/sources/ruby/crm/app/javascript/packs/hello.ts(37,19)
      TS2307: Cannot find module '../hello'.
webpack: Failed to compile.
```

What did I miss?

**Comment by mapreal19** [comment]
@johansmitsnl in your `webpacker.yml` do you have `ts` as an extension?

**Comment by johansmitsnl** [comment]
@mapreal19 yes:

```yaml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .tsx
    - .ts
    - .vue
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```
