### ISSUE TITLE
Print javascript error when executing webpacker

### ISSUE THREAD

**Issue by siegy22** [rails/webpacker#2042]
Hey there!

I ran into this weird behaviour when using rails' `ActionDispatch::SystemTestCase`. The error I get was the following:

```
ActionView::Template::Error: Webpacker can't find application in <project>/public/packs-test/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}

    app/views/index/show.html.erb:5
```

This happened to me on Travis CI. But none of the above 4 steps solved my issue.

The issue here was, that I didn't fetch my javascript dependencies. For me it was kind of obvious in a second thought. But at the same time, I didn't see the error that happened when webpacker automatically tried to compile the javascript pack.

IMO when the `webpack` command fails, the output should be in the error. 

What do you guys think?

**Comment by jakeNiemiec** [comment]
This might give more context: https://github.com/rails/webpacker/issues/1759#issuecomment-462878582

**Comment by siegy22** [comment]
Is there a way to enable the stacktrace for the webpack command?

**Comment by jakeNiemiec** [comment]
You can enable error details by configuring your stats object: https://webpack.js.org/configuration/stats/

In order to debug, you would need to provide more info from `webpacker.yml`, `package.json` etc.

**Comment by siegy22** [comment]
I'm using rails 6.0.0.beta3
I didn't touch my `webpacker.yml`, it was generated with `rails new <project> --webpack=vue`:
```yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .vue
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that versions and hashed value of the package contents in the project's package.json
  check_yarn_integrity: false

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```

And here's my package.json:

```js
{
  "name": "<project>",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0-alpha",
    "@rails/ujs": "^6.0.0-alpha",
    "@rails/webpacker": "^4.0.2",
    "babel-plugin-module-resolver": "^3.2.0",
    "color-convert": "^2.0.0",
    "deepmerge": "^3.2.0",
    "flexboxgrid": "^6.3.1",
    "highcharts": "^7.1.0",
    "lodash": "^4.17.11",
    "reset-css": "^4.0.1",
    "vue": "^2.6.10",
    "vue-loader": "^15.7.0",
    "vue-template-compiler": "^2.6.10",
    "vuex": "^3.1.0"
  },
  "scripts": {
    "lint": "eslint app/javascript --ext .js --ext .vue"
  },
  "version": "0.1.0",
  "devDependencies": {
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.2.2",
    "webpack-dev-server": "^3.2.1"
  }
}
```
