### ISSUE TITLE
`rails assets:precompile` does not regenerate assets in some scenarios

### ISSUE THREAD

**Issue by etagwerker** [rails/webpacker#2049]
Hi there! 

I found a weird issue in my environment:

- rails (= 5.1.6)
- webpacker (= 4.0.2)
- webpack (= 4.29.6) 

My configuration looks like this:

```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
```

My current business requirements make it impossible for me to call `rails assets:clobber` right before calling `rails assets:precompile`. I realize that might be the most common scenario.

I make a small change to one of my JS files and then call `rails assets:precompile`. The first time it works fine. Subsequent calls to `rails assets:precompile` will not generate new packs.

I believe that the issue is related to the webpacker cache or _something off in my configuration_.

I tried a few things.

I tried changing this value in `config/application.rb`:

```
config.assets.version = "3.7"
```

But that didn't compile anything. 

Also, I tried to change my `webpacker.yml` to be like this:

```
production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: false
```

After many attempts trying to figure out what was the issue, the only thing that work was doing this in my server: `rm -rf tmp/cache/webpacker/`

```
$ rm -rf tmp/cache/webpacker/
$ RAILS_ENV=production bundle exec rake assets:precompile
Compiling…
Compiled all packs in /data/apps/ror/pws/releases/20190412020508/public/packs
```

Is there something wrong with my configuration? 

Thanks in advance!
