### ISSUE TITLE
wrong port for HMR sockjs-node

### ISSUE THREAD

**Issue by GuillaumeM59** [rails/webpacker#2067]
Hi!
It's seems that sockjs get rails port instead webpack-dev-server config port (webpacker.yml).

├─ @rails/webpacker@4.0.2
├─ webpack-cli@3.3.1
├─ webpack-dev-middleware@3.6.2
├─ webpack-dev-server@3.3.1
├─ webpack@4.30.0

webpack.yml (dev-server part):

```
  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: 0.0.0.0
    port: 3036
    public: 0.0.0.0:3036
    hmr: true
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/
```

got rails error: ActionController::RoutingError (No route matches [GET] "/sockjs-node/info"):
got js console error: [WDS] Disconnected!

It try to connect sockets in 3007 (rails server port) instead 3036.

![Capture d’écran de 2019-04-23 10-29-45](https://user-images.githubusercontent.com/15214746/56566518-22dd7180-65b3-11e9-92b8-fc5df2cf2159.png)

This return "ok" status if i change port manually and resend request.

To be sure, i reran 'rails webpacker:binstubs' and said me identical files...

Where change config to resolve websocket connection crashes?
Thanks

**Comment by amiuhle** [comment]
Caused by this PR: https://github.com/webpack/webpack-dev-server/pull/1664

**Comment by ionutzp** [comment]
@amiuhle is right the line https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L211
changes your port when using 0.0.0.0 as a host ...

**Comment by DEfusion** [comment]
I saw this merged PR https://github.com/webpack/webpack-dev-server/pull/1792/files but can't get it to work with webpacker. Has anyone had any luck with this? I have `webpack-dev-server` version 3.3.1

**Comment by uetomae-naohiko-mori** [comment]
What about specifying `sockPort`?

```
  dev_server:
    https: false
    host: 0.0.0.0
    port: 3036
    sockPort: 3036
```
