### ISSUE TITLE
Loading Background Images inside CSS

### ISSUE THREAD

**Issue by abepark01** [rails/webpacker#2121]
I am using webpacker `4.0.7` and seem to be having loading images inside my CSS file.

The following code worked fine in webpacker `3.5.5`.
Any thoughts?

I have the following directory structure
```
-packs
  logo.js
-css
  logo.css
-images
  logos/Startup/image.png
```

**logo.css**
```css
.icon-imgEndorsify {
   background-image: url("../images/logos/Startups/image.png");
 }
```

**logo.js**
```es6
import '../css/logos.css';
 
require.context('../images', true);
```

The manifest shows that the image has been loaded, but the CSS doesn't seem to be loading the image.
