### ISSUE TITLE
bin/webpack --watch compile changes but not returning any log

### ISSUE THREAD

**Issue by KevinKP17** [rails/webpacker#2278]
Hi this behaviour occur whenever i'm running the command `bin/webpack --watch`
versions:
1. webpack v4.39.1
2. node v10.16.0

## Problem
webpack will print the initial compilation with expected behaviour
```
Compilation  starting…


webpack is watching the files…


Compilation  finished

Hash: 82474d18ad3846150416
Version: webpack 4.39.1
Time: 5645ms
Built at: 09/10/2019 11:05:40 AM
                                  Asset       Size       Chunks             Chunk Names
                          manifest.json  380 bytes               [emitted]  
    mobile/home-82474d18ad3846150416.js    335 KiB  mobile/home  [emitted]  mobile/home
mobile/home-82474d18ad3846150416.js.map    390 KiB  mobile/home  [emitted]  mobile/home
Entrypoint mobile/home = mobile/home-82474d18ad3846150416.js mobile/home-82474d18ad3846150416.js.map
[./app/javascript/packs/mobile/home.js] 1.08 KiB {mobile/home} [built]
[./app/stylesheets/packs/mobile/home.scss] 969 bytes {mobile/home} [built] [failed] [1 error]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {mobile/home} [built]
    + 1 hidden module
```
the problem lies when i try to change any files changes that are included in the entry points. with following steps:
1. i change the js files eg: add some `console.log`
2. run save
3. reload the browser; wait for several seconds
4. the changes applied
5. no logs or output printed on the terminal
6. there are no any message such as `Compilation starting ..` or etc, just nothing happened

## webpacker.yml
```
development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: 0.0.0.0
    port: 3035
    public: 10.10.10.12:3035
    hmr: true
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'
      poll: true
```

## webpack/environment.js
```
const { environment } = require('@rails/webpacker')
const path = require('path');
const webpack = require('webpack');

const aliasConfig = {
  resolve: {
    alias: {
      '@gulp': path.resolve('gulp/assets'),
      '@asset': path.resolve('app/assets'),
      '@css': path.resolve('app/stylesheets'),
      '@views': path.resolve('app/views')
    }
  }
}

environment.plugins.append('Provide', new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery'
}));

const optimizationConfig = {
  optimization: {
    runtimeChunk: 'single',
    splitChunks: {
      chunks: 'all',
      cacheGroups: {
       vendor: {
         test: /[\\/]node_modules[\\/]/,
         name: 'vendors',
         chunks: 'all'
       }
     }
    }
  }
}
environment.config.merge(optimizationConfig);

environment.config.merge(aliasConfig);

module.exports = environment
```

## webpack/development.js
```
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')
const StylelintPlugin =require('stylelint-webpack-plugin')
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

environment.plugins.append('StylelintPlugin', new StylelintPlugin({
  context: 'app',
  files: [
    'stylesheets/**/*.s?(a|c)ss',
    'views/**/*.s?(a|c)ss'
  ]
}));

environment.plugins.append('BundleAnalyzerPlugin', new BundleAnalyzerPlugin({
  analyzerHost: '10.10.10.12',
  analyzerMode: 'static',
  analyzerPort: 8088
}));

module.exports = environment.toWebpackConfig()
```

i'm trying to run other command such as `bin/webpack --watch --progress --verbose --info-verbosity verbose` but there are no changes.

many thanks
