### ISSUE TITLE
Background Url not working in scss files

### ISSUE THREAD

**Issue by bpdarlyn** [rails/webpacker#2327]
## Folder Structure

- javascript
    - main-app
        - images
            - asset2.png
        - styles
            welcome.scss
    - packs
        - pages
            - welcome
                - index.scss

```ruby
# view welcome.html.erb
<%= javascript_pack_tag 'pages/welcome/index' %>
```

```scss
// packs/welcome/index.scss
@import "./../../../main-app/styles/welcome";
```

```scss
// main-app/styles/welcome.scss
.culture {
  background-image: url('../images/Asset2.png');
}
```

## The error
```bash
Module not found: 
Error: Can't resolve '../images/Asset2.png' 
in '/app/javascript/packs/pages/welcome'
```
  
## The manifest.json
```json
{"media/main-app/images/Asset2.png": "/packs/media/main-app/images/Asset2-7040fa15ac8a960a3b9fc3d7f8939a64.png"}
```

## How do I fix?
```scss
// put the path the manifest.json 
.culture {
  background-image: url('media/main-app/images/Asset2.png');
}
```

## Do you know why is happening this ?
