### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR when accessing via https

### ISSUE THREAD

**Issue by petebytes** [rails/webpacker#2370]
webpacker.yml
https: true
restart server

Request URL: https://localhost:3035/sockjs-node/info?t=1573948782814
generates:
This site can’t provide a secure connectionlocalhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

over http
http://localhost:3035/sockjs-node/info?t=1573948782814
{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":1329639071}

I do not have an option on Chrome or Firefox to accept (self signed cert)

```
dev_server:
  https: true
  host: localhost
  port: 3035
  public: localhost:3035
  hmr: true
  # Inline should be set to true if using HMR
  inline: true
  overlay: true
  compress: true
  disable_host_check: true
  use_local_ip: false
  quiet: false
  headers:
    'Access-Control-Allow-Origin': '*'
  watch_options:
    ignored: '**/node_modules/**'
```

OS: macOS Catalina 10.15.1
