### ISSUE TITLE
Webpacker ignores compilation of tests and try to recompile it when running rspec

### ISSUE THREAD

**Issue by Loremaster** [rails/webpacker#2373]
This issue is quite weird. I use webpacker + vue + typescript + jest. 

Basically I added few changes to fix an issue where importing vue components in jest tests would show error `TS2307: Cannot find module ../MyComponent.vue`. I was able to fix this error but somehow webpacker doesn't seem to precompile tests and every time I run tests in CI it tries to compile tests again.

The changes I did:
**app/javascript/@types/vue-shim.d.ts**
```diff
+++ b/app/javascript/@types/vue-shim.d.ts
+declare module "*.vue" {
+  import Vue from "vue";
+  export default Vue;
+}
```

**jest.config.js**
```diff
module.exports = {
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  modulePathIgnorePatterns: ["<rootDir>/.*/__mocks__"],
  setupFiles: ["<rootDir>/jest_setup.ts", "jest-date-mock"],
  moduleDirectories: ["node_modules", "<rootDir>/app/javascript"],
  transform: {
    "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
    ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest",
    "^.+\\.tsx?$": "ts-jest",
  },
  testRegex: "/__tests__/.*\\.(ts|tsx|js)$",
  transformIgnorePatterns: ["node_modules/(?!bootstrap-vue|epic-spinners)"],
  snapshotSerializers: ["<rootDir>/node_modules/jest-serializer-vue"],
  testPathIgnorePatterns: ["<rootDir>/app/assets", "<rootDir>/config/webpack/test.js", "<rootDir>/vendor"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/app/javascript/$1",
    "\\.(css|less)$": "identity-obj-proxy",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "<rootDir>/app/javascript/__mocks__/fileMock.js",
  },
  restoreMocks: true,
  globals: {
     "ts-jest": {
-      tsConfig: "tsconfig.jest.json",
+      tsConfig: "tsconfig.json",
       babelConfig: true,
       diagnostics: false,
    },
  },
}
```

**tsconfig.jest.json**
```diff
--- a/tsconfig.jest.json
-{
-  "extends": "./tsconfig",
-  "compilerOptions": {
-    "module": "commonjs",
-    "esModuleInterop": true
-  }
-}
```

**tsconfig.json**
```diff
{
  "compilerOptions": {
    "baseUrl": "./app/javascript",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom", "es2015.promise", "es2017"],
    "moduleResolution": "node",
    "module": "es2015",
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "target": "es5",
    "allowJs": true,
    "downlevelIteration": true,
    "strict": true
  },
-  "exclude": ["**/*.spec.ts", "node_modules", "vendor", "public", "**/__mocks__/index.ts"],
+  "exclude": ["node_modules", "vendor", "public"],
  "compileOnSave": false
}
```

Those are all changes I did. Now in CI I compile tests and then run them. It looks something along these lines:

```bash
$ NODE_ENV=test bundle exec rails webpacker:compile --trace
$ bundle exec rspec
```

It used to compile tests and then run rspec tests. It compiles tests and then compiles those again when running rspec. Any ideas how to fix that?

Here is my wepbacker config just in case:

```yaml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: ["app/assets"]

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: true

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .tsx
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
    - .module.sass
    - .module.scss
    - .module.css

development:
  <<: *default
  compile: false

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: true

  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  # You might want to set to false for local development
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```
