### ISSUE TITLE
Compilation fails due to 'Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by Volosh1n** [rails/webpacker#2375]
Hi!

Recently project moved from Sprockets to Webpacker. All styles were moved from `app/assets/stylesheets` to `app/webpack/stylesheets` (webpack folder name was configured in `webpacker.yml`).

In `webpacker.yml` I only added following configs:
```yml
source_path: app/webpack
resolved_paths: ['app/assets'] # because we still using images from app/assets/images
extract_css: true
```
And Bootstrap/JQuery/Popper added to webpacker too.

Current file structure:
```
app
├── # ...
└── webpack
    ├── packs
    │   ├── application.js
    │   ├── landings.scss
    │   └── services.scss
    └── stylesheets
```

Files like `landings.scss` just imports many other styles from `app/webpacker/stylesheets/` folder with many `@import`s. But the following issue occurred many times:
![webpacker_screenshot](https://user-images.githubusercontent.com/16169679/69623921-5eaa4f00-104c-11ea-91f9-2ace4d685c44.png)

For the first time, we just cropped large CSS bundles (that's why there is no application.scss), which was included by controller name (for example, `services_controller` requires only `services.css`, etc.) and it temporary fixed problem. But with style files growing, this problem returned. Splitting CSS no longer helps, large CSS bundle crashes compilation.

Has anyone faced this issue too? Can stack size be increased in config? I found flag `--stack-size=1000`, but it didn't help with any value.
Also, I checked all styles files for recursive `@import`s, but everything is fine.

**Comment by jakeNiemiec** [comment]
In order to help debug, could you please post as much as you can of:
- `services.scss`
- `./config/webpack/environment.js`
- `./config/webpacker.yml`
- `./app/javascript/packs/application.js` 
- the full error message (even the parts you wouldn’t think of as relevant)

It looks like it's having a problem with [acornjs](https://github.com/acornjs/acorn), how are you using this?

**Comment by Volosh1n** [comment]
@jakeNiemiec , thanks for reply!
Actually, we don't use acorn explicitly anywhere, just Webpacker.
About error: screenshot covers it almost fully - there are some lines about acorn.js after that screenshot and then default webpack output about built packs, nothing more about error, unfortunately.

Here is some files you requested:

* `./config/webpacker.yml`:
```yml
default: &default
  source_path: app/webpack
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false
  resolved_paths: ['app/assets']
  cache_manifest: false
  extract_css: true

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true

staging:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
```

* `./config/webpack/environment.js`:
```js
const { environment } = require('@rails/webpacker')
const webpack = require('webpack')

environment.loaders.get('sass').use.splice(-1, 0, {
  loader: 'resolve-url-loader'
});

environment.loaders.get('sass').use.find(item => item.loader === 'sass-loader').options.includePaths = ['node_modules']

environment.plugins.prepend('Provide', new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery',
  Popper: ['popper.js', 'default']
}))

module.exports = environment
```

* `services.scss`:
```scss
@import '../stylesheets/app/base/colors';
@import '../stylesheets/app/base/variables';
@import '../stylesheets/app/bootstrap/module';
@import '../stylesheets/app/base/module';
@import '../stylesheets/app/aos/module';
@import '../stylesheets/app/slick/slick';
@import '../stylesheets/app/components/module';
@import '../stylesheets/app/modules/services/module';
@import '../stylesheets/app/layout/module';
@import '../stylesheets/app/utils/helpers';
@import '../stylesheets/app/custom';
@import '../stylesheets/app/ie';
```

* `app/webpack/packs/application.js`:
```js
import 'bootstrap/dist/js/bootstrap.bundle'
import 'jquery/dist/jquery.slim'
import 'popper.js/dist/esm/popper'
```

Also, I want to add that as we use `resolved_paths: ['app/assets']`, we can have access to `app/assets/fonts` or `app/assets/images` from scss files with something like `background-image: image-url('~images/social_icons/twitter.svg');`. Could this affect compilation?
