### ISSUE TITLE
Upgrading to 1.1 breaks

### ISSUE THREAD

**Issue by MatthiasRMS** [rails/webpacker#251]
After running bundle update (and noticing that I went from 1.0 to 1.1), relaunching my server (locally), I have this error:
`Can't find application.js in /my_app/public/packs/manifest.json. Is webpack still compiling?`

When specifying 1.0 in my gemfile, it works fine. When moving back to 1.1, error comes back. 

I have a basic setup, similar to what you advise in the readme. 
Happy to invite one of the maintainer to our private repo.

**Comment by gauravtiwari** [comment]
@MatthiasRMS You would need to re-run `bundle exec rails webpacker:install` and `bundle exec rails webpacker:install:{react, angular, vue}` if you have added these too.

**Comment by BoleLee** [comment]
I also met this error: 
```Can't find application.js in /my_app/public/packs/manifest.json. Is webpack still compiling?```

ubuntu 16.04
rails: 5.0.2
the main step that I take:
```
Gemfile: 
gem 'webpacker', github: 'rails/webpacker'

bundle install
rails webpacker:install && rails webpacker:install:vue
```

when I add ```<%= javascript_pack_tag 'application' %>```, it went this error. 

Besides, I already install ```yarn```, which version is 0.22, however, when I run ```rails webpacker:install && rails webpacker:install:vue```, it comes with some messages: 
```
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
```

**Comment by gauravtiwari** [comment]
@BoleLee Is yarn available in the path? Can you verify please if `yarn --version` runs okay?

**Comment by metaskills** [comment]
New to Yarn and such, but I noticed the latest 0.22 of Yarn uses the `yarn` bin name which is installed and n my path. But I noticed the `./bin/yarn` stub wants to call `yarnpkg` seen here: https://github.com/rails/webpacker/blob/master/lib/install/bin/yarn.tt#L5

 I have no such binary called `yarnpkg` did things change?

**Comment by inchr** [comment]
I've the same problem.

I've checked the prerequisites and are all ok. Any idea ?

**Comment by inchr** [comment]
@gauravtiwari it says:
yarn --version
0.21.3

**Comment by ytbryan** [comment]
`yarnpkg` and `yarn` refers to the same thing. If you have yarn installed,  I would check if your `webpack-dev-server` port is free. At `development.server.yml`, try to change it from the default 8080 to something else.

**Comment by metaskills** [comment]
Is `yarnpkg` installed for everyone? It was certainly not installed for me.

**Comment by gauravtiwari** [comment]
@metaskills How did you install yarn - homebrew or npm? https://yarnpkg.com/lang/en/docs/install/ I have installed with homebrew and both binaries are available.

**Comment by metaskills** [comment]
> How did you install yarn - homebrew or npm

Neither.... MacPorts.

**Comment by gauravtiwari** [comment]
Hmm, then I guess it's something to do with MacPorts 😄

**Comment by metaskills** [comment]
Honestly tho... what is the primary binary name? Is one an alias for the other? Are they different?

**Comment by inchr** [comment]
I used homebrew...btw now seems to be ok after I've started again the webpack server in development.

**Comment by ytbryan** [comment]
anyway,  Gaurav changed `yarnpkg` to `yarn` in this PR https://github.com/rails/webpacker/pull/264/files#diff-d4fa2613404db474328053641eaae683

**Comment by gauravtiwari** [comment]
Closing since this doesn't feel like an issue anymore 👍  Feel free to reopen

**Comment by jarvisjohnson** [comment]
FYI for others coming across this - I had these errors deploying to Ubuntu 16.04.  
I had installed Yarn via npm and `yarn --version` gave me 0.15.3.
So I [installed Yarn from source](https://yarnpkg.com/lang/en/docs/install/#linux-tab), which resulted in Yarn version 0.23.4 being installed, which worked with Webpacker.

**Comment by gauravtiwari** [comment]
We should check the yarn version too durint install.

**Comment by jarvisjohnson** [comment]
Agreed - an 'outdated Yarn' message would be helpful in that situation

**Comment by sergeyvdovareize** [comment]
@BoleLee have you resolved your issue? I have the same error message and can't find out what to do.

**Comment by gauravtiwari** [comment]
@sergeyvdovareize Are you compiling webpack assets using `./bin/webpack` or `./bin/webpack-dev-server`? What version of webpacker are you using? Could you please paste your `config/webpacker.yml`?

**Comment by sergeyvdovareize** [comment]
@gauravtiwari 
I didn't change anything there.
```yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```

Here is my folders architecture
![image](https://image.prntscr.com/image/bVSmHuyMRhOkWgpQDHPn8A.png)

When i run `./bin/webpack` it says 
`No such file or directory - .../node_modules/.bin/webpack (Errno::ENOENT)`
