### ISSUE TITLE
Proxy sends requests to 3035:443 (webpacker, docker & https)

### ISSUE THREAD

**Issue by pch** [rails/webpacker#2520]
Hi,

I'm trying to run rails (5.2) + webpacker (5.0.1) in Docker. The setup uses `https` and `webpack_dev_server` runs in a separate container.

The problem is that `dev_server_proxy` doesn't forward the host & port correctly and ends up requesting `webpack_dev_server:3035:443`, which fails with `Name or service not known`.

Full trace:

```
2020-04-03 09:52:45 +0000: Rack app error handling request { GET /packs/js/application-cd4eae35e792d878d598.js }
#<SocketError: Failed to open TCP connection to webpack_dev_server:3035:443 (getaddrinfo: Name or service not known)>
/usr/local/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect'
/usr/local/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
/usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/lib/ruby/2.4.0/net/http.rb:882:in `start'
/gems/ruby/2.4.0/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:79:in `session'
/gems/ruby/2.4.0/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:64:in `response'
/gems/ruby/2.4.0/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:31:in `headers'
/gems/ruby/2.4.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:120:in `perform_request'
/gems/ruby/2.4.0/gems/webpacker-5.0.1/lib/webpacker/dev_server_proxy.rb:21:in `perform_request'
/gems/ruby/2.4.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/gems/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:524:in `call'
/gems/ruby/2.4.0/gems/puma-4.3.3/lib/puma/configuration.rb:228:in `call'
/gems/ruby/2.4.0/gems/puma-4.3.3/lib/puma/server.rb:682:in `handle_request'
/gems/ruby/2.4.0/gems/puma-4.3.3/lib/puma/server.rb:472:in `process_client'
/gems/ruby/2.4.0/gems/puma-4.3.3/lib/puma/server.rb:328:in `block in run'
/gems/ruby/2.4.0/gems/puma-4.3.3/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

## Possible solution

The following change seems to fix the issue, at least in this case, but I haven't tested it with a non-https setup:

```diff
# https://github.com/rails/webpacker/blob/master/lib/webpacker/dev_server_proxy.rb

  def perform_request(env)
    if env["PATH_INFO"].start_with?("/#{public_output_uri_path}") && dev_server.running?
-     env["HTTP_HOST"] = env["HTTP_X_FORWARDED_HOST"] = env["HTTP_X_FORWARDED_SERVER"] = dev_server.host_with_port
+     env["HTTP_HOST"] = env["HTTP_X_FORWARDED_HOST"] = env["HTTP_X_FORWARDED_SERVER"] = dev_server.host
+     env["HTTP_X_FORWARDED_PORT"] = dev_server.port.to_s
      env["HTTP_X_FORWARDED_PROTO"] = env["HTTP_X_FORWARDED_SCHEME"] = dev_server.protocol
      unless dev_server.https?
        env["HTTPS"] = env["HTTP_X_FORWARDED_SSL"] = "off"
      end
      env["SCRIPT_NAME"] = ""

      super(env)
    else
      @app.call(env)
    end
  end
```

---

### webpacker.yml

```yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: true
    host: webpack_dev_server
    port: 3035
    public: 0.0.0.0:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'
```

### docker-compose.yml

```yml
version: '3'
services:
  main_app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "9292:9292"
    volumes:
      - app-sync:/usr/src/app:nocopy
      - gem_cache:/gems:delegated

  webpack_dev_server:
    depends_on:
      - main_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "/usr/src/app/bin/webpack-dev-server"
    ports:
      - 3035:3035
    volumes:
      - app-sync:/usr/src/app:nocopy
      - gem_cache:/gems:delegated
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
```

Is this a bug or is it a problem with my config?
