### ISSUE TITLE
javascript_pack_path not resolving to /packs

### ISSUE THREAD

**Issue by poloka** [rails/webpacker#254]
Utilizing webpacker-1.1 with rails-4.2.7.1, created packs under app/javascript/packs with modules under app/javascript.  Upon webpacking, get files in the public/packs folder with the manifest.json noting
```
{
  "myfile.js": "myfile-f69686cde06a17cfebd6.js"
}
```
But when my app/views/myview is rendered
```
!!!
%html{:lang => 'en-us'}
  %head
    %meta{:content => 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}
    %title My Test Example
    %meta{:charset => 'utf-8'}
  %body
    = javascript_pack_tag 'myfile'
```
It returns
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-us">
<head>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <title>My Test Example</title>
  <meta charset="utf-8"/>
</head>
<body>
<script src="/javascripts/myfile-f69686cde06a17cfebd6.js"></script>
</body>
</html>

```
The javascript served is from `javascripts` and not the expected `packs` folder.  Is there something wrong with my config or an issue with webpacker?

**Configurations**:

**paths.yml:**
```
# Restart webpack-watcher or webpack-dev-server if you make changes here
default: &default
  config: config/webpack
  entry: packs
  output: public
  manifest: manifest.json
  node_modules: node_modules
  source: app/javascript
  extensions:
    - .coffee
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg

development:
  <<: *default

test:
  <<: *default
  manifest: manifest-test.json

production:
  <<: *default
```

**shared.js**:
```
// Note: You must restart bin/webpack-watcher for changes to take effect

const webpack = require('webpack');
const path = require('path');
const process = require('process');
const glob = require('glob');
const extname = require('path-complete-extname');
const ManifestPlugin = require('webpack-manifest-plugin')

var distDir = process.env.WEBPACK_DIST_DIR;

if(distDir === undefined) {
  distDir = 'packs'
}

config = {
  entry: glob.sync(path.join('app', 'javascript', 'packs', '*.js*')).reduce(
    function(map, entry) {
      const basename = path.basename(entry, extname(entry));
      const localMap = map;
      localMap[basename] = path.resolve(entry);
      return localMap;
    }, {}
  ),

  output: { filename: '[name].js', path: path.resolve('public', distDir) },

  module: {
    rules: [
      {
        test: /\.jsx?(.erb)?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: [
            'react',
            [ 'latest', { 'es2015': { 'modules': false } } ]
          ]
        }
      },
      {
        test: /.erb$/,
        enforce: 'pre',
        exclude: /node_modules/,
        loader: 'rails-erb-loader',
        options: {
          runner: 'DISABLE_SPRING=1 bin/rails runner'
        }
      },
    ]
  },

  plugins: [
    new webpack.EnvironmentPlugin(Object.keys(process.env)),
    new ManifestPlugin({
      fileName: 'manifest.json'
    })
  ],

  resolve: {
    extensions: [ '.js' ],
    modules: [
      path.resolve('app/javascript'),
      path.resolve('node_modules')
    ]
  },

  resolveLoader: {
    modules: [ path.resolve('node_modules') ]
  }
};

module.exports = {
  distDir: distDir,
  config: config
};
```

**production.js**:
```
// Note: You must restart bin/webpack-watcher for changes to take effect

const webpack = require('webpack');
const merge   = require('webpack-merge');
const CompressionPlugin = require('compression-webpack-plugin');

const sharedConfig = require('./shared.js');

module.exports = merge(sharedConfig.config, {
  output: { filename: '[name]-[chunkhash].js' },

  plugins: [
    new webpack.LoaderOptionsPlugin({
      minimize: true
    }),
    new webpack.optimize.UglifyJsPlugin(),
    new CompressionPlugin({
      asset: '[path].gz[query]',
        algorithm: 'gzip',
      test: /\.(js|css|svg|eot|ttf|woff|woff2)$/
    })
  ]
});
```
