### ISSUE TITLE
HMR does full page reload

### ISSUE THREAD

**Issue by akoskm** [rails/webpacker#2637]
Using webpacker 4.2.2, with HRM turned on:

```
# Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'
```

HMR seems to be working:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/3111627/85259203-e92f2180-b468-11ea-8c3d-67735a5ea026.png">

Inside the slim template I'm using the product_variants React component as:

```
- content_for :head
  = javascript_pack_tag 'product_variants'
```

However, I'm facing a few problems:

### Browser does full page reload:

In the logs, I see that the message is received and processed, right before navigating to the same page:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/3111627/85261737-e8988a00-b46c-11ea-8917-bbd8f4c20663.png">

however,  the browser reloads the whole page.

### Different output when running with WEBPACKER_DEV_SERVER_HOT:

The component I'm receiving for HMR is different when running `bundle exec bin/webpack-dev-server` vs when running it with the above flag:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/3111627/85259822-fef11680-b469-11ea-9203-290675ed6ad6.png">

What is the correct way to run the dev server when HMR is enabled in the configuration file?
What causes the browser to reload the whole page?
