### ISSUE TITLE
Importing custom font fails with "Failed to decode downloaded font" and  "OTS parsing error: invalid version tag"

### ISSUE THREAD

**Issue by zedtux** [rails/webpacker#2680]
I'm running a Rails 5.2.3 application with webpacker 4.0.7 (in Docker) and I'm trying to import a custom font (an icomoon in this case) but it fails when loading the page in Chrome with the following:

```
Failed to decode downloaded font: https://webpack.mydomain.co/packs/media/fonts/icomoon-1a1860f858537c4e85d73a1d6f6b5c61.ttf
OTS parsing error: invalid version tag
```

I already have the `font-awesome` font working but from an npm package.

Here is my `config/webpacker.yml`:

```yaml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

local:
  <<: *default
  compile: true

  # Verifies that versions and hashed value of the package contents in the project's package.json
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    # HTTPS is managed by Nginx (see docker-compose.yml)
    https: false
    # This host is used by the webpacker gem in order to contact the webpack-dev-server
    # In our case we give the container name so that a TCP connection test works
    # and Rails understand that he doesn't have to run webpack.
    host: webpack
    port: 3035
    # Public host where to access/download the packs.
    public: webpack.mydomain.co
    # Hot Module Replacement
    hmr: true
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  # Compile test packs to a separate directory
  public_output_path: packs


production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```

And I have added the following to the `config/webpack/environment.js`:

```javascript
/* Fonts */
environment.loaders.append('fonts', {
  test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
  exclude: /node_modules/,
  use: [
    {
      loader: 'file-loader',
      options: {
        name: 'fonts/[name].[ext]'
      }
    }
  ]
})
```
_The `exclude` option is necessary as it breaks font-awesome otherwise._

And finally, I have created an `app/javascript/fonts` folder with my `icomoon.eot`, `icomoon.svg`, `icomoon.ttf`, and `icomoon.woff` files and create the following `app/javascript/stylesheets/icomoon.scss` SCSS file:

```sass
@font-face {
  font-family: icomoon;
  src:  url('../fonts/icomoon.eot');
  src:  url('../fonts/icomoon.eot#iefix')   format('embedded-opentype'),
        url('../fonts/icomoon.ttf')         format('truetype'),
        url('../fonts/icomoon.woff')        format('woff'),
        url('../fonts/icomoon.svg#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

[class^="icon-"], [class*=" icon-"] {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: 'icomoon' !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-pil:before {
  content: "\e904";
}
```

Here is the webpack dev server output:

```
webpack_1    |                                                     Asset       Size       Chunks             Chunk Names
...
webpack_1    |                                         fonts/icomoon.eot   1.26 KiB               [emitted]
webpack_1    |                                         fonts/icomoon.svg  960 bytes               [emitted]
webpack_1    |                                         fonts/icomoon.ttf    1.1 KiB               [emitted]
webpack_1    |                                        fonts/icomoon.woff   1.17 KiB               [emitted]
webpack_1    |                                             manifest.json   3.15 KiB               [emitted]
...
webpack_1    |  media/fonts/icomoon-0abebcad628fb3c7a1d716c6e23958f9.eot   63 bytes               [emitted]
webpack_1    |  media/fonts/icomoon-1a1860f858537c4e85d73a1d6f6b5c61.ttf   63 bytes               [emitted]
webpack_1    | media/fonts/icomoon-7fd23b6b550864230d42421fe315007f.woff   64 bytes               [emitted]
webpack_1    |  media/fonts/icomoon-e1ebeaf9d38c061974d9aede6cae7a35.svg  129 bytes               [emitted]
...
```

So it looks like Chrome is loading the font from that path `media/fonts/icomoon-1a1860f858537c4e85d73a1d6f6b5c61.ttf` which is 63 bytes only, so I guess a wrong path, and therefore is failing to load it.

 * Why do I have both the `fonts/icomoon.ttf` and `media/fonts/icomoon-1a1860f858537c4e85d73a1d6f6b5c61.ttf` ?
 * What should I change in my config/code in order to get it working?
