### ISSUE TITLE
Set webpacker dev port with environment variable

### ISSUE THREAD

**Issue by johncadengo** [rails/webpacker#2847]
I'm setting a custom env variable for the web packer dev port, with the following syntax

```WEBPACKER_DEV_SERVER_PORT=3036```

When I run `./bin/webpack-dev-server` it appears to be serving it on the correct port according to the env variable (although the terminal output is incorrect and still shows the default port of 3035). 

My webpacker.yml looks like this

```
development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'
```

How do I allow `port` and `public` to use environment variables?
