### ISSUE TITLE
When is the Webpacker documentation for engines restored?

### ISSUE THREAD

**Issue by DiegoOrejuela** [rails/webpacker#2886]
Documentation was deleted by #2826

**Comment by pedrofurtado** [comment]
Hey, @DiegoOrejuela ! 👋 

Webpacker 6.x made some major breaking changes, that invalidates (in most cases) the old docs present in 5.x versions.

We are turning 6.x releases more stable for a while, and then it will be possible to create docs for it 🤝

**Comment by DiegoOrejuela** [comment]
Thanks. I am attentive.

**Comment by patricklindsay** [comment]
@basex Was that using `5.x` or `6.x`?

@pedrofurtado Can we reopen this for visibility so that we get some docs on engines created before 6 is released?

**Comment by basex** [comment]
The engines documentation can be restored as it is https://github.com/rails/webpacker/blob/fb9aa9622a7760cb6c21d304250e1c9b92b1a6ac/docs/engines.md

I'm using webpacker 6 in production in separate engines and just works. I set to serve the packs from the root public folder, I have my webpacker.yml on the engines with this setup:

```yml
default: &default
  source_path: app/packs
  source_entry_path: entrypoints
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
```

The rest of the webpacker.yml can stay as it is. I had to still keep the original webpacker.yml in the root config.
