### ISSUE TITLE
Load ttf font files in Webpacker 5.4

### ISSUE THREAD

**Issue by philipriley** [rails/webpacker#3077]
I have an issue with Webpacker 5.4 similar to this closed issue -> https://github.com/rails/webpacker/issues/2680

I am using Monaco Editor in my application and use monaco-editor-webpack-plugin to take care of the webpack side of things. The editor loads fine in the app, but it cannot load a font file called codicon.ttf, which is microsofts own icon font. Here is a my webpacker.yml config: 

``` yaml
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  additional_paths: []
  cache_manifest: false

  extract_css: false

  static_assets_extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .tiff
  - .ico
  - .svg
  - .eot
  - .otf
  - .ttf
  - .woff
  - .woff2

  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: false

  dev_server:
    https: false
    host: localhost
    port: 3035
    public: 0.0.0.0:3035
    hmr: false
    inline: false
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default
  compile: false
  cache_manifest: true
  extract_css: true

```
I have a custom config file for webpack plugins, where I have registered the monaco-editor-webpack-plugin

``` js
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = {	
  plugins: [
    new MonacoWebpackPlugin({
	languages: ['yaml'],
        features: [
          '!accessibilityHelp',
          ... other disabled features
	],
      filename: "[name].[contenthash].bundle.js"
   }),
  ]
};
```
Which I import into environment.js
``` js
const { environment } = require('@rails/webpacker');
const customConfig = require('./custom');

environment.config.merge(customConfig);
// environment.loaders.prepend('ttf', {  
//     test: /\.ttf$/,
//     loader: 'file-loader',
//     options: {
//       outputPath: 'media',
//     },
// })

module.exports = environment;
```
As you can see in environment.js, I have commented out configuration for loading ttf files. When commented out, webpack generates the following:
`media/codicon/codicon-0e0f4555.ttf   69.4 KiB               [emitted] `
and my manifest looks like this
``` json
{
  "application.js": "/packs/js/application-1723b206576300adfe3b.js",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-1723b206576300adfe3b.js"
      ]
    }
  },
  "media/codicon/codicon.ttf": "/packs/media/codicon/codicon-0e0f4555.ttf"
}
```
If I uncomment the config in environment.js, webpack generates this:
```
media/a1966df93d6d5a16acfa9db746791f41.ttf   80 bytes               [emitted]
media/codicon/codicon-0e0f4555.ttf   69.4 KiB               [emitted]  
```
the manifest is changed to 
```
{
  "application.js": "/packs/js/application-b91367f08917778c23f5.js",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-b91367f08917778c23f5.js"
      ]
    }
  },
  "media/codicon.ttf": "/packs/media/0e0f4555ac984d9d78c1a07738e98d58.ttf",
  "media/codicon/codicon.ttf": "/packs/media/codicon/codicon-75b9c3f5.ttf"
}
```
The browser tries to load media/a1966.....ttf but I get
```
Failed to decode downloaded font: http://localhost/packs/media/a1966df93d6d5a16acfa9db746791f41.ttf
section-0:1 OTS parsing error: invalid sfntVersion: 1836016757
```
It is only 80 bytes so obviously something wasn't generated correctly.

As a trial, I changed `environment.loaders.prepend` to `environment.loaders.append` and webpack outputs
```
media/0e0f4555ac984d9d78c1a07738e98d58.ttf   69.4 KiB               [emitted]
media/codicon/codicon-75b9c3f5.ttf   86 bytes               [emitted]
```
and the browser now tries but fails to load media/codicon/codicon-75b9c3f5.ttf  instead.... which is now only 86 bytes.

How can I get webpacker configured to load the correct file? I'm absolutely not a webpack expect, which is why I really like webpacker. Any help would be appreciated.
