### ISSUE TITLE
Rack  <EOFError: end of file reached> when running side-car Rails & Webpacker in dev mode on k8s

### ISSUE THREAD

**Issue by ndrean** [rails/webpacker#3126]
I run on a Minikube cluster in the same pod Rails in dev mode with Webpacker side-car. The Webpacker container keeps dying.

 I get `[frontend] ℹ ｢wdm｣: wait until bundle finished` and then the error `Rack app ("GET /packs/media/images/.... #<EOFError: end of file reached>`.

If I run Rails alone, everything renders ok, with the same image (a very standard one. However, I need Webpacker since I want HMR.

My config is almost the same as when using `docker-compose` with both services, Rails and Webpacker, which works like a charm.

The `webpack.yml` is untouched.
I tried mounting a shared volume for the folder '/tmp/cache/webpack' without more success.

My config is (side-car)

```yml
containers:
   - name: frontend
      image: builder-dev
     command: ["./bin/webpack-dev-server"]
     ports:
        - containerPort: 3035
     environment:
        - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
 - name: backend
   image: builder-dev
   command: ["bundle"]
   args: ["exec", "rails", "server", "-b", "0.0.0.0"]
   ports:
      - containerPort: 3000
   environment:
       - WEBPACKER_DEV_SERVER_HOST: frontend    <- ref to the container name
 ```
