### ISSUE TITLE
Importing css file in application.scss throws an error, while importing it in application.js works fine

### ISSUE THREAD

**Issue by shadydealer** [rails/webpacker#3132]
#Problem
Trying to get [bootstrap-icons](https://icons.getbootstrap.com) to work by importing the bootstrap-icons/font/bootstrap-icons.css in the application.scss instead of having to import it in application.js (as some people in [stackoverflow suggested](https://stackoverflow.com/questions/60727460/using-bootstrap-icons-in-rails-6-with-webpacker) )

I spent all day yesterday, trying to make it so we don't import css files in the application.js because the following error occurs when importing it in the application.scss:

```Ruby
ERROR in ./app/javascript/packs/application.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/resolve-url-loader??ref--6-3!./node_modules/sass-loader/dist/cjs.js??ref--6-4!./app/javascript/packs/application.scss)
Module not found: Error: Can't resolve './fonts/bootstrap-icons.woff2?856008caa5eb66df68595e734e59580d' in '/home/shadydealer/work/beme/platform/app/javascript/packs'
 @ ./app/javascript/packs/application.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/resolve-url-loader??ref--6-3!./node_modules/sass-loader/dist/cjs.js??ref--6-4!./app/javascript/packs/application.scss) 4:36-109
 @ ./app/javascript/packs/application.scss
 @ multi ./app/javascript/packs/application.js ./app/javascript/packs/application.scss

ERROR in ./app/javascript/packs/application.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/resolve-url-loader??ref--6-3!./node_modules/sass-loader/dist/cjs.js??ref--6-4!./app/javascript/packs/application.scss)
Module not found: Error: Can't resolve './fonts/bootstrap-icons.woff?856008caa5eb66df68595e734e59580d' in '/home/shadydealer/work/beme/platform/app/javascript/packs'
 @ ./app/javascript/packs/application.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/resolve-url-loader??ref--6-3!./node_modules/sass-loader/dist/cjs.js??ref--6-4!./app/javascript/packs/application.scss) 5:36-108
 @ ./app/javascript/packs/application.scss
 @ multi ./app/javascript/packs/application.js ./app/javascript/packs/application.scss
```

The whole problem comes from the following lines in their code:

```Css
node_modules/bootstrap_icons/font/fonts/bootstrap_icons.css

@font-face {
  font-family: "bootstrap-icons";
  src: url("./fonts/bootstrap-icons.woff2?856008caa5eb66df68595e734e59580d") format("woff2"),
url("./fonts/bootstrap-icons.woff?856008caa5eb66df68595e734e59580d") format("woff");
}
```

if we change those paths to:

```Css
@font-face {
  font-family: "bootstrap-icons";
  src: url("../../../node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff2?856008caa5eb66df68595e734e59580d") format("woff2"),
url("../../../node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff?856008caa5eb66df68595e734e59580d") format("woff");
}
```

importing the css in the application.js works fine, but I don't want to mix my css files with my js files and changing the paths in the url calls in the node_module is not a solution for obvious reasons.

I tried using [resolve-url-loader](https://github.com/bholloway/resolve-url-loader) as some people have suggested (and also [webpack](https://webpack.js.org/loaders/sass-loader/#problems-with-url) themselves) but I couldn't get it to work. I tried doing it by modyfing the config/webpack/environment.js:

```Javascript
const { environment } = require('@rails/webpacker')

environment.loaders.get("sass").use.splice(-1, 0, {
  loader: "resolve-url-loader"
});
environment.loaders.get("moduelSass").use.splice(-1, 0, {
  loader: "resolve-url-loader"
});
module.exports = environment
```

But it changed nothing.

Using 
webpacker 5.4.0
rails 6.1.4
