### ISSUE TITLE
Configure CSS Modules in Webpacker

### ISSUE THREAD

**Issue by gabalicious** [rails/webpacker#368]
How can I get the example to work with Rails 5.1 and webpacker?

```js
// app/javascript/components/ChatWindow.js
import React from  'react';
import Style from './ChatWindow.scss'
class ChatWindow extends React.Component {
  constructor (props) {

  }
  render () {
    return (
      <div className={Style.ChatWindow}>

      </div>
    );
  }
}
export default ChatWindow;
```

```scss
// app/javascript/components/ChatWindow.scss
.ChatWindow {
  width: 100%;
  min-height: 10%;
  border: black 1px solid;
  background: red;
}

```

```js
// config/webpack/loaders/sass.js
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const { env } = require('../configuration.js')

module.exports = {
  test: /\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      { loader: 'css-loader', options: {
        modules: true,
        sourceMap: true,
        importLoaders: 2,
        localIdentName: '[name]__[local]___[hash:base64:5]'
      }
    },
    'postcss-loader',
    'sass-loader'
  ]
})
}
```
