### ISSUE TITLE
"Invalid Host Header" in JS console since upgrading to Webpacker 2.0

### ISSUE THREAD

**Issue by catskull** [rails/webpacker#424]
Since upgrading to webpacker 2.0, I'm getting a bunch of "invalid host header" errors in the JS console. Other sources online have said to pass `disableHostCheck true` when starting webpack-dev-server. I've modified my webpacker.yml to look like this:

```
development:
  <<: *default

  dev_server:
    host: 0.0.0.0
    port: 8080
    disableHostCheck: true
    https: false
```

And then development.js, I've modified the devServer object to include this line: 
`disableHostCheck: settings.dev_server.disableHostCheck,`

Is that appropriate? Is anyone else getting these errors?
