### ISSUE TITLE
ES6 import/exports error

### ISSUE THREAD

**Issue by niks123123** [rails/webpacker#511]
Greeting!
ES6 imports/exports doesn't work for me.
**application.html.haml:**
```haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wbp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

```

**config/webpack.yml**:
```yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    host: 0.0.0.0
    port: 8080
    https: false

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default
```
**app/assets/javascripts/packs/test.js**:
```JavaScript
export function Foo(text) {
	console.log(text);
}
```
**app/assets/javascripts/packs/app.js**:
```JavaScript
import {Foo} from 'test';

Foo('Hello world!');
```
**browser console error:**
```
SyntaxError: import declarations may only appear at top level of a module  app.self-4f3316f3d39d8000942274eda5f401aaa80817093299efdc4e881abf3547a376.js:1
SyntaxError: export declarations may only appear at top level of a module  test.self-6c41c871ac4cb01daf716bcc056199cfb679ac71a90f870a2ab5ca88b119399d.js:1
```
Running webpack and rails via foreman. **Procfile**:
```
web: bundle exec rails s
webpacker: ./bin/webpack-dev-server
```
**Gemfile**:
```Ruby
gem 'webpacker', git: 'https://github.com/rails/webpacker.git'
```
Ruby version: **2.4.0p0**
Rails version: **5.1.1**
