### ISSUE TITLE
Heroku failing to precompile assets

### ISSUE THREAD

**Issue by te-chris** [rails/webpacker#611]
I'm getting a werid error that I can't really interpret - heroku is claiming there's no 'node' available. This is on a brand new Rails 5.1 app with webpack configured - brand new project, just setting up staging and test CI and deployments. Have removed all the legacy gems with the intention of all assets going through webpack.

When I push to heroku it dumps the following error:

```
remote: -----> Installing yarn-0.22.0
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        /usr/bin/env: ‘node’: No such file or directory
remote:        I, [2017-08-02T16:35:01.694424 #387]  INFO -- : Writing /tmp/build_bf3a7fa6aadb85acb76d970339d09d76/public/assets/application-4686b818638f6733ef663ff96aa2bb9a7c1ee1fa04ffcb01931142cc7bce910a.js
remote:        I, [2017-08-02T16:35:01.695637 #387]  INFO -- : Writing /tmp/build_bf3a7fa6aadb85acb76d970339d09d76/public/assets/application-4686b818638f6733ef663ff96aa2bb9a7c1ee1fa04ffcb01931142cc7bce910a.js.gz
remote:        I, [2017-08-02T16:35:01.706320 #387]  INFO -- : Writing /tmp/build_bf3a7fa6aadb85acb76d970339d09d76/public/assets/application-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css
remote:        I, [2017-08-02T16:35:01.706871 #387]  INFO -- : Writing /tmp/build_bf3a7fa6aadb85acb76d970339d09d76/public/assets/application-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css.gz
remote:        vendor/bundle/bin/rake: No such file or directory - node
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
```

When I try and run `heroku run yarn` or `heroku run node` both run without issue. When I run `assets:precompile` locally and with `heroku run` it runs without issue.

This is my webpacker.yml file:

```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    host: 0.0.0.0
    port: 8080
    https: false

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default
```

My Gemfile:
```
ruby '2.4.1'

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.2'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  gem 'dotenv-rails'
  gem 'rspec-rails', '~> 3.5'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'guard'
  gem 'guard-rspec', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```
