### ISSUE TITLE
Rails server breaks after Webpacker installed

### ISSUE THREAD

**Issue by kozhin** [rails/webpacker#762]
Hi there!

I'm trying the latest Webpacker gem and found that it breaks Puma in my case. Puma runs but browser shows error.

**Environment:**
Debian linux inside Docker container with Rails app.
Development at localhost. Webpack-dev-server is not running.

**Steps to reproduce:**
- create new rails app
- add webpacker gem
- run webpacker:install
- start Rails Server
- get following error:

```
Puma caught this error: Cannot assign requested address - connect(2) for [::1]:3035 (Errno::EADDRNOTAVAIL)
/root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/socket.rb:1198:in `__connect_nonblock'
/root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/socket.rb:1198:in `connect_nonblock'
/root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/socket.rb:56:in `connect_internal'
/root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/socket.rb:137:in `connect'
/root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/socket.rb:627:in `block in tcp'
/root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/socket.rb:227:in `each'
/root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/socket.rb:227:in `foreach'
/root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/socket.rb:617:in `tcp'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/webpacker-3.0.1/lib/webpacker/dev_server.rb:9:in `running?'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/webpacker-3.0.1/lib/webpacker/dev_server_proxy.rb:7:in `rewrite_response'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-proxy-0.6.2/lib/rack/proxy.rb:57:in `call'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.3/lib/rails/engine.rb:522:in `call'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```
**Notice:** If I start webpack-dev-server inside Docker container manually everything starts to work just as expected.

I guess, it is somehow connected with the following:
> In development, Webpacker compiles on demand rather than upfront by default. This happens when you refer to any of the pack assets using the Webpacker helper methods. That means you don't have to run any separate process. Compilation errors are logged to the standard Rails log.

In previous versions of Webpacker I haven't seen this problem.

**Comment by lourenci** [comment]
Same here.

I just created a new rails app with the `rails new app --webpack` command and I've got the same exactly problem. The puma cannot serve the app until I start `webpack-dev-server`.

I'm running in a docker container too.

**Comment by caseyprovost** [comment]
Try this file combo:

docker-compose.yml
```yaml
version: '2'
services:
  web:
    build: .
    command: foreman start -f Procfile.dev
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - '8080:8080'
    depends_on:
      - postgres
    env_file:
      - '.env.docker'
  postgres:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: YOUR_DB_USER
      POSTGRES_DB: YOUR_DB
      POSTGRES_PASSWORD: YOUR_DB_PASSWORD
```

Procfile.dev

```
web: bin/puma -C config/puma.rb
webpack_dev_server: ./bin/webpack-dev-server

```

**Comment by kozhin** [comment]
@caseyprovost thanks! Your solution worked for me.

I wonder, why does Puma break if Webpacker compiles on demand without running additional process for that:

>  ...you don't have to run any separate process...

**Comment by gauravtiwari** [comment]
@caseyprovost It's because `localhost` isn't available inside docker container by default, which makes this check fail: 

https://github.com/rails/webpacker/blob/master/lib/webpacker/dev_server.rb#L13 (more info here: https://ruby-doc.org/stdlib-1.8.7/libdoc/socket/rdoc/Socket.html)

Please change config/webpacker.yml to use: 

```yml
  dev_server:
    host: 0.0.0.0 # or the docker IP
```

and restart your container. You can change the `network_mode` to `host` if wish to use `localhost`

**Comment by kozhin** [comment]
@gauravtiwari thanks for clarification! I've fixed my Docker container. Additionally to your suggestion I had to do the following:

1. Run Rails Server with **-b 0.0.0.0**
2. Start webpack-dev-server with **--disable-host-check true**

BTW, **disableHostCheck** is ignored if placed in webpacker.yml:
```
dev_server:
    host: 0.0.0.0
    port: 3035
    hmr: false
    https: false
    disableHostCheck: true
```
