### ISSUE TITLE
Any help doc about converting rails old assets pipeline to webpack?

### ISSUE THREAD

**Issue by gamesover** [rails/webpacker#803]
May I know is there any wiki doc about how to convert old assets pipeline to webpack? My rails is 4.2.6.

**Comment by curvo** [comment]
Hi @gamesover, I've been going through this process on the SCSS side thus far and am happy to help if you have any specific questions?  

And otherwise, what are you looking for exactly?  I'm considering at least writing up the approach we've used here at User Testing for this... but maybe there's more to share depending on the need.  Thanks

**Comment by gamesover** [comment]
Hi @curvo , thanks for your reply. Our current js is structured by http://nandovieira.com/using-es2015-with-asset-pipeline-on-ruby-on-rails + a little vuejs. To be frank, we have an quite large and old rails project. To convert to SPA is a bit mission impossible. However, we want to use webpack to structure our js code to be easier to maintain and debug. If we cannot convert old code to vuejs, I hope we can write all new code in vuejs.

**Comment by curvo** [comment]
Hi @gamesover - we've got a ten year old project ourselves at User Testing.  We are currently on Ruby 2.3.4 running Rails 4.2.9.  

I just launched webpack to production on thursday but we decided just to compile a couple of main scss manifest files that were pulling in an internal design system toolkit which moved from being checked in to now dynamically being pulled in via yarn and then compiled by webpack.  

There have been a couple of hiccups along the way, and a few of them popped up after launching.  I have written some internal documentation that I would be happy to share with you personally via email but I am also pulling that stuff together for a blog post which then I can link to from here.  I should be posting to our blog this week so I will link that here and hopefully it may help with potential issues you may face, especially with deployment. 

On our side, I have not yet jumped into compiling js with webpack, but we have haml, es6, angular 1.4 (3 different approaches) and a bunch supporting js in our app.  We do plan to move all of that over though, so, I'm sure to be tackling some of the same problems you face.

Off the bat, at least for CSS, I will say that we decided to put our packs in `app/assets/packs`.  When we build with webpacker they go into `public/development/assets/packs`, `public/staging/assets/packs` or `public/assets/packs` for production.  All of the pack use is for logged in states currently except for our login page itself (See: https://www.usertesting.com/users/sign_in).

We chose this structure mainly for it's simplicity within our current code base.  At first I thought I needed a separate directory, but by staying within assets itself, we realized it would be less confusing to the entire team as it eliminates the general need to move so many things around.  I'll elaborate more on that in our blog.

So for now, please email if you're like (bcase@usertesting.com) or as I mentioned, I will circle back here and post links to our blog posts when they are released (if that is allowed in this thread? @gauravtiwari ?).

**Comment by gauravtiwari** [comment]
@curvo Thanks for detailed example 🍰  Yes, please feel free to post as long as they are relevant ;)

Most of the things are same as asset pipeline except you will be using webpack to compile the JS code, which means you can write modern JS (thanks to babel). The only convention here is anything that you want to link in your view like say a calendar module on a calendar page, you would add that to `app/javascript/packs` folder - these are webpack entries. All source files can live under `app/javascript` though. 

```yml
app/javascript: 
  src: # can be called src or anything of your choice
    #.. all files that are JS source, can be structured anyway you like
  packs: 
    # all webpack entry files, can be nested in sub-folders as well
    # this is where you can require source files and bootstrap them, like vue component render on DOMLoad etc.
```

I am going to close this one since this is not an issue.

**Comment by gamesover** [comment]
@curvo , thanks so much for your detailed reply. I am expecting to see your blog then :) Definitely, I can learn and apply to my current project. Thank you again.

**Comment by curvo** [comment]
@gauravtiwari I'm curious about the `app/javascript` convention.  It feels like the wrong place to put sass/image files but maybe I'm just hanging onto older asset pipeline thinking?  That's another reason why leaving all of the source files in the `app/assets` directories in our project seemed to make sense.  

For new Rails 5+ projects is the idea that you might do something like this?

```yaml
app/javascript:
    src:
        javascripts:
        stylesheets:
        images:
    packs:
```
It just bothers me a little bit having stylesheets and images under javascript, but like I said, maybe I'm holding onto old conventions?  What patterns are people following?

For our Rails 4.2.9 project we are using this structure:

```yaml
app/assets:
    fonts:                       # current font assets
    images:                    # current image assets
    javascripts:              # current js assets
    media:                      # current audio assets
    packs:                      # new packs entry point
    shared_webpack_manifests:  # shared sub-pack manifest files
    stylesheets:             # current scss/css files
 ```
I admit that `shared_webpack_manifests` isn't the greatest name but we needed a place to put snippets that are shared between packs but are essentially just sub-pack like files.

One big advantage to this structure for our team is that we don't have to move our current assets from their `app/assets/SUBDIRECTORIES` to `app/javascripts` (or any place else).  This conceptually seems to simplify the process of migrating files from sprockets to webpack.

Anyway, just wondering what you all are seeing/thinking around all of this?  Thanks.
