### ISSUE TITLE
Support toggling auto-compilation without modifying webpacker.yml

### ISSUE THREAD

**Issue by bessey** [rails/webpacker#905]
Please correct me if I am wrong, but I believe at present there is no way - without modifying source controlled files - to change the `compile` setting in webpacker.yml.

I think this has a pretty obvious benefit, some (frontend) developers will want the complexity of hot module reloading, while others (backend) prefer the simplicity of `bin/rails s` = GO!

I naively tried this:
```yml
# ...
development:
  <<: *default
  compile: <%= Settings.webpack_compile %>

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 8080
    public: localhost:8080
    # This is necessary because webpack doesn't extract CSS without explicitly disabling HMR
    hmr: <%= !Settings.webpack_compile %>
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false
# ...
```

But of course no interpolation is performed, so this doesn't work. Looking at the code I can see it would be challenging to achieve this without something to the effect of

1. Pre-processing webpacker.yml with `rails runner`
2. Saving to tmp/
3. Pointing webpack at this file

I admit, that's a bit excessive for supporting what is probably the only bit of config in webpacker.yml that different developers might have different configurations for. But I can't think of many alternatives. Perhaps deep merging a .gitignore'd `webpacker.local.yml`? At least that could be done in `bin/webpacker` without the Rails environment. Still needs a temp file though. Or alternatively, perhaps an environment variable? I could live with
```bash
WEBPACKER_COMPILE=false bin/rails s
bin/webpack-dev-server
```
