### ISSUE TITLE
Difficulty hot reloading with dockerized configuration

### ISSUE THREAD

**Issue by SonofNun15** [rails/webpacker#978]
We are running `bundle exec rails s` in one docker container with webpacker 3.0, rails 5.1, and ruby 2.2.

This is our webpack.yml development configuration:
```
development:
  <<: *default
  compile: true

  dev_server:
    https: false
    host: localhost
    port: 8080
    public: localhost:8080
    hmr: true
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false
```

We have a second docker container that simply runs `./bin/webpack-dev-server`

With the above yml hot reloading does not work, no websocket is opened.

When we change the host and public from `localhost` to `webpack` (the name of the webpack-dev-server container), rails spits out an error about an empty manifest file.

Here's our docker-compose.yml file:

```
version: '2'
services:
  webserver:
    tty: true
    stdin_open: true
    build: .
    command: script/start
    ports:
      - "3000:3000"
    links:
      - webpack
    environment:
      - RAILS_ENV=development
  webpack:
    build: .
    command: bin/webpack-dev-server
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      - NODE_ENV=development
```

`script/start` literally just runs `bundle exec rails s`

The Dockerfile mounts the main repository directory, runs bundle install, runs yarn install.

Does anybody have any suggestions? It is hard to tell what configuration informs the dev server how / where to run and what configuration tells webpacker where to find the dev server. This configuration may be shared and perhaps that is part of the problem since this docker setup splits webpacker and the dev server into separate virtual containers?

For reference, the Webpacker error from rails when host is `webpack`:
```
Webpacker::Manifest::MissingEntryError in Tos#view
Showing /app/app/views/tos/view.html.erb where line #4 raised:

Webpacker can't find application.js in /app/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. Webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your Webpack configuration is not creating a manifest.
Your manifest contains:
{
}
```
